/*
###############################################################
#  Generated by:      Cadence Innovus 19.10-p002_1
#  OS:                Linux x86_64(Host ID hurricane)
#  Generated on:      Fri Sep 23 21:48:58 2022
#  Design:            BLOCK_DIGITAL
#  Command:           saveNetlist ../output/BLOCK_DIGITAL_phys.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : N-2017.09
// Date      : Fri Sep 23 15:14:52 2022
/////////////////////////////////////////////////////////////
module sar_adc_logic_12bit_v4_single_input_conv_v1_0 (
	SAR_REG0, 
	WP, 
	COMP, 
	PULSE, 
	WP_RSTN);
   output SAR_REG0;
   output [11:0] WP;
   input COMP;
   input [11:1] PULSE;
   input WP_RSTN;

   // Internal wires
   wire FE_ECON10_n52;
   wire FE_ECON9_data_from_adc0_1;
   wire FE_ECON8_data_from_adc0_2;
   wire FE_ECON7_data_from_adc0_3;
   wire FE_ECON6_data_from_adc0_4;
   wire FE_ECON5_data_from_adc0_5;
   wire FE_ECON4_data_from_adc0_6;
   wire FE_ECON3_data_from_adc0_7;
   wire FE_ECON2_data_from_adc0_8;
   wire FE_ECON1_data_from_adc0_9;
   wire FE_ECON0_data_from_adc0_10;
   wire LOGIC0;

   DLY2HDLLX0 FE_ECOC10_n52 (.A(WP[0]),
	.Q(FE_ECON10_n52));
   DLY2HDLLX0 FE_ECOC9_data_from_adc0_1 (.A(WP[1]),
	.Q(FE_ECON9_data_from_adc0_1));
   DLY2HDLLX0 FE_ECOC8_data_from_adc0_2 (.A(WP[2]),
	.Q(FE_ECON8_data_from_adc0_2));
   DLY2HDLLX0 FE_ECOC7_data_from_adc0_3 (.A(WP[3]),
	.Q(FE_ECON7_data_from_adc0_3));
   DLY2HDLLX0 FE_ECOC6_data_from_adc0_4 (.A(WP[4]),
	.Q(FE_ECON6_data_from_adc0_4));
   DLY2HDLLX0 FE_ECOC5_data_from_adc0_5 (.A(WP[5]),
	.Q(FE_ECON5_data_from_adc0_5));
   DLY2HDLLX0 FE_ECOC4_data_from_adc0_6 (.A(WP[6]),
	.Q(FE_ECON4_data_from_adc0_6));
   DLY2HDLLX0 FE_ECOC3_data_from_adc0_7 (.A(WP[7]),
	.Q(FE_ECON3_data_from_adc0_7));
   DLY2HDLLX0 FE_ECOC2_data_from_adc0_8 (.A(WP[8]),
	.Q(FE_ECON2_data_from_adc0_8));
   DLY2HDLLX0 FE_ECOC1_data_from_adc0_9 (.A(WP[9]),
	.Q(FE_ECON1_data_from_adc0_9));
   DLY2HDLLX0 FE_ECOC0_data_from_adc0_10 (.A(WP[10]),
	.Q(FE_ECON0_data_from_adc0_10));
   DFRRSQHDLLX0 I39 (.C(LOGIC0),
	.D(LOGIC0),
	.Q(WP[0]),
	.RN(WP_RSTN),
	.SN(PULSE[1]));
   DFRRSQHDLLX0 I38 (.C(FE_ECON10_n52),
	.D(COMP),
	.Q(WP[1]),
	.RN(WP_RSTN),
	.SN(PULSE[2]));
   DFRRSQHDLLX0 I37 (.C(FE_ECON9_data_from_adc0_1),
	.D(COMP),
	.Q(WP[2]),
	.RN(WP_RSTN),
	.SN(PULSE[3]));
   DFRRSQHDLLX0 I36 (.C(FE_ECON8_data_from_adc0_2),
	.D(COMP),
	.Q(WP[3]),
	.RN(WP_RSTN),
	.SN(PULSE[4]));
   DFRRSQHDLLX0 I35 (.C(FE_ECON7_data_from_adc0_3),
	.D(COMP),
	.Q(WP[4]),
	.RN(WP_RSTN),
	.SN(PULSE[5]));
   DFRRSQHDLLX0 I34 (.C(FE_ECON6_data_from_adc0_4),
	.D(COMP),
	.Q(WP[5]),
	.RN(WP_RSTN),
	.SN(PULSE[6]));
   DFRRSQHDLLX0 I33 (.C(FE_ECON5_data_from_adc0_5),
	.D(COMP),
	.Q(WP[6]),
	.RN(WP_RSTN),
	.SN(PULSE[7]));
   DFRRSQHDLLX0 I32 (.C(FE_ECON4_data_from_adc0_6),
	.D(COMP),
	.Q(WP[7]),
	.RN(WP_RSTN),
	.SN(PULSE[8]));
   DFRRSQHDLLX0 I31 (.C(FE_ECON3_data_from_adc0_7),
	.D(COMP),
	.Q(WP[8]),
	.RN(WP_RSTN),
	.SN(PULSE[9]));
   DFRRSQHDLLX0 I30 (.C(FE_ECON2_data_from_adc0_8),
	.D(COMP),
	.Q(WP[9]),
	.RN(WP_RSTN),
	.SN(PULSE[10]));
   DFRRSQHDLLX0 I10 (.C(FE_ECON1_data_from_adc0_9),
	.D(COMP),
	.Q(WP[10]),
	.RN(WP_RSTN),
	.SN(PULSE[11]));
   DFRSQHDLLX0 I0 (.C(FE_ECON0_data_from_adc0_10),
	.D(COMP),
	.Q(WP[11]),
	.SN(WP_RSTN));
   LOGIC0DHDLL I41 (.Q(LOGIC0));
   DFRQHDLLX0 I42 (.C(PULSE[1]),
	.D(COMP),
	.Q(SAR_REG0));
endmodule

module sar_adc_logic_12bit_v4_single_input_conv_v1_1 (
	SAR_REG0, 
	WP, 
	COMP, 
	PULSE, 
	WP_RSTN);
   output SAR_REG0;
   output [11:0] WP;
   input COMP;
   input [11:1] PULSE;
   input WP_RSTN;

   // Internal wires
   wire FE_ECON10_n52;
   wire FE_ECON9_data_from_adc0_1;
   wire FE_ECON8_data_from_adc0_2;
   wire FE_ECON7_data_from_adc0_3;
   wire FE_ECON6_data_from_adc0_4;
   wire FE_ECON5_data_from_adc0_5;
   wire FE_ECON4_data_from_adc0_6;
   wire FE_ECON3_data_from_adc0_7;
   wire FE_ECON2_data_from_adc0_8;
   wire FE_ECON1_data_from_adc0_9;
   wire FE_ECON0_data_from_adc0_10;
   wire LOGIC0;

   DLY2HDLLX0 FE_ECOC10_n52 (.A(WP[0]),
	.Q(FE_ECON10_n52));
   DLY2HDLLX0 FE_ECOC9_data_from_adc0_1 (.A(WP[1]),
	.Q(FE_ECON9_data_from_adc0_1));
   DLY2HDLLX0 FE_ECOC8_data_from_adc0_2 (.A(WP[2]),
	.Q(FE_ECON8_data_from_adc0_2));
   DLY2HDLLX0 FE_ECOC7_data_from_adc0_3 (.A(WP[3]),
	.Q(FE_ECON7_data_from_adc0_3));
   DLY2HDLLX0 FE_ECOC6_data_from_adc0_4 (.A(WP[4]),
	.Q(FE_ECON6_data_from_adc0_4));
   DLY2HDLLX0 FE_ECOC5_data_from_adc0_5 (.A(WP[5]),
	.Q(FE_ECON5_data_from_adc0_5));
   DLY2HDLLX0 FE_ECOC4_data_from_adc0_6 (.A(WP[6]),
	.Q(FE_ECON4_data_from_adc0_6));
   DLY2HDLLX0 FE_ECOC3_data_from_adc0_7 (.A(WP[7]),
	.Q(FE_ECON3_data_from_adc0_7));
   DLY2HDLLX0 FE_ECOC2_data_from_adc0_8 (.A(WP[8]),
	.Q(FE_ECON2_data_from_adc0_8));
   DLY2HDLLX0 FE_ECOC1_data_from_adc0_9 (.A(WP[9]),
	.Q(FE_ECON1_data_from_adc0_9));
   DLY2HDLLX0 FE_ECOC0_data_from_adc0_10 (.A(WP[10]),
	.Q(FE_ECON0_data_from_adc0_10));
   DFRRSQHDLLX0 I39 (.C(LOGIC0),
	.D(LOGIC0),
	.Q(WP[0]),
	.RN(WP_RSTN),
	.SN(PULSE[1]));
   DFRRSQHDLLX0 I38 (.C(FE_ECON10_n52),
	.D(COMP),
	.Q(WP[1]),
	.RN(WP_RSTN),
	.SN(PULSE[2]));
   DFRRSQHDLLX0 I37 (.C(FE_ECON9_data_from_adc0_1),
	.D(COMP),
	.Q(WP[2]),
	.RN(WP_RSTN),
	.SN(PULSE[3]));
   DFRRSQHDLLX0 I36 (.C(FE_ECON8_data_from_adc0_2),
	.D(COMP),
	.Q(WP[3]),
	.RN(WP_RSTN),
	.SN(PULSE[4]));
   DFRRSQHDLLX0 I35 (.C(FE_ECON7_data_from_adc0_3),
	.D(COMP),
	.Q(WP[4]),
	.RN(WP_RSTN),
	.SN(PULSE[5]));
   DFRRSQHDLLX0 I34 (.C(FE_ECON6_data_from_adc0_4),
	.D(COMP),
	.Q(WP[5]),
	.RN(WP_RSTN),
	.SN(PULSE[6]));
   DFRRSQHDLLX0 I33 (.C(FE_ECON5_data_from_adc0_5),
	.D(COMP),
	.Q(WP[6]),
	.RN(WP_RSTN),
	.SN(PULSE[7]));
   DFRRSQHDLLX0 I32 (.C(FE_ECON4_data_from_adc0_6),
	.D(COMP),
	.Q(WP[7]),
	.RN(WP_RSTN),
	.SN(PULSE[8]));
   DFRRSQHDLLX0 I31 (.C(FE_ECON3_data_from_adc0_7),
	.D(COMP),
	.Q(WP[8]),
	.RN(WP_RSTN),
	.SN(PULSE[9]));
   DFRRSQHDLLX0 I30 (.C(FE_ECON2_data_from_adc0_8),
	.D(COMP),
	.Q(WP[9]),
	.RN(WP_RSTN),
	.SN(PULSE[10]));
   DFRRSQHDLLX0 I10 (.C(FE_ECON1_data_from_adc0_9),
	.D(COMP),
	.Q(WP[10]),
	.RN(WP_RSTN),
	.SN(PULSE[11]));
   DFRSQHDLLX0 I0 (.C(FE_ECON0_data_from_adc0_10),
	.D(COMP),
	.Q(WP[11]),
	.SN(WP_RSTN));
   LOGIC0DHDLL I41 (.Q(LOGIC0));
   DFRQHDLLX0 I42 (.C(PULSE[1]),
	.D(COMP),
	.Q(SAR_REG0));
endmodule

module sar_adc_logic_12bit_v4_single_input_conv_v1_2 (
	SAR_REG0, 
	WP, 
	COMP, 
	PULSE, 
	WP_RSTN);
   output SAR_REG0;
   output [11:0] WP;
   input COMP;
   input [11:1] PULSE;
   input WP_RSTN;

   // Internal wires
   wire FE_ECON10_n52;
   wire FE_ECON9_data_from_adc0_1;
   wire FE_ECON8_data_from_adc0_2;
   wire FE_ECON7_data_from_adc0_3;
   wire FE_ECON6_data_from_adc0_4;
   wire FE_ECON5_data_from_adc0_5;
   wire FE_ECON4_data_from_adc0_6;
   wire FE_ECON3_data_from_adc0_7;
   wire FE_ECON2_data_from_adc0_8;
   wire FE_ECON1_data_from_adc0_9;
   wire FE_ECON0_data_from_adc0_10;
   wire LOGIC0;

   DLY2HDLLX0 FE_ECOC10_n52 (.A(WP[0]),
	.Q(FE_ECON10_n52));
   DLY2HDLLX0 FE_ECOC9_data_from_adc0_1 (.A(WP[1]),
	.Q(FE_ECON9_data_from_adc0_1));
   DLY2HDLLX0 FE_ECOC8_data_from_adc0_2 (.A(WP[2]),
	.Q(FE_ECON8_data_from_adc0_2));
   DLY2HDLLX0 FE_ECOC7_data_from_adc0_3 (.A(WP[3]),
	.Q(FE_ECON7_data_from_adc0_3));
   DLY2HDLLX0 FE_ECOC6_data_from_adc0_4 (.A(WP[4]),
	.Q(FE_ECON6_data_from_adc0_4));
   DLY2HDLLX0 FE_ECOC5_data_from_adc0_5 (.A(WP[5]),
	.Q(FE_ECON5_data_from_adc0_5));
   DLY2HDLLX0 FE_ECOC4_data_from_adc0_6 (.A(WP[6]),
	.Q(FE_ECON4_data_from_adc0_6));
   DLY2HDLLX0 FE_ECOC3_data_from_adc0_7 (.A(WP[7]),
	.Q(FE_ECON3_data_from_adc0_7));
   DLY2HDLLX0 FE_ECOC2_data_from_adc0_8 (.A(WP[8]),
	.Q(FE_ECON2_data_from_adc0_8));
   DLY2HDLLX0 FE_ECOC1_data_from_adc0_9 (.A(WP[9]),
	.Q(FE_ECON1_data_from_adc0_9));
   DLY2HDLLX0 FE_ECOC0_data_from_adc0_10 (.A(WP[10]),
	.Q(FE_ECON0_data_from_adc0_10));
   DFRRSQHDLLX0 I39 (.C(LOGIC0),
	.D(LOGIC0),
	.Q(WP[0]),
	.RN(WP_RSTN),
	.SN(PULSE[1]));
   DFRRSQHDLLX0 I38 (.C(FE_ECON10_n52),
	.D(COMP),
	.Q(WP[1]),
	.RN(WP_RSTN),
	.SN(PULSE[2]));
   DFRRSQHDLLX0 I37 (.C(FE_ECON9_data_from_adc0_1),
	.D(COMP),
	.Q(WP[2]),
	.RN(WP_RSTN),
	.SN(PULSE[3]));
   DFRRSQHDLLX0 I36 (.C(FE_ECON8_data_from_adc0_2),
	.D(COMP),
	.Q(WP[3]),
	.RN(WP_RSTN),
	.SN(PULSE[4]));
   DFRRSQHDLLX0 I35 (.C(FE_ECON7_data_from_adc0_3),
	.D(COMP),
	.Q(WP[4]),
	.RN(WP_RSTN),
	.SN(PULSE[5]));
   DFRRSQHDLLX0 I34 (.C(FE_ECON6_data_from_adc0_4),
	.D(COMP),
	.Q(WP[5]),
	.RN(WP_RSTN),
	.SN(PULSE[6]));
   DFRRSQHDLLX0 I33 (.C(FE_ECON5_data_from_adc0_5),
	.D(COMP),
	.Q(WP[6]),
	.RN(WP_RSTN),
	.SN(PULSE[7]));
   DFRRSQHDLLX0 I32 (.C(FE_ECON4_data_from_adc0_6),
	.D(COMP),
	.Q(WP[7]),
	.RN(WP_RSTN),
	.SN(PULSE[8]));
   DFRRSQHDLLX0 I31 (.C(FE_ECON3_data_from_adc0_7),
	.D(COMP),
	.Q(WP[8]),
	.RN(WP_RSTN),
	.SN(PULSE[9]));
   DFRRSQHDLLX0 I30 (.C(FE_ECON2_data_from_adc0_8),
	.D(COMP),
	.Q(WP[9]),
	.RN(WP_RSTN),
	.SN(PULSE[10]));
   DFRRSQHDLLX0 I10 (.C(FE_ECON1_data_from_adc0_9),
	.D(COMP),
	.Q(WP[10]),
	.RN(WP_RSTN),
	.SN(PULSE[11]));
   DFRSQHDLLX0 I0 (.C(FE_ECON0_data_from_adc0_10),
	.D(COMP),
	.Q(WP[11]),
	.SN(WP_RSTN));
   LOGIC0DHDLL I41 (.Q(LOGIC0));
   DFRQHDLLX0 I42 (.C(PULSE[1]),
	.D(COMP),
	.Q(SAR_REG0));
endmodule

module sar_adc_logic_12bit_v4_single_input_conv_v1_3 (
	SAR_REG0, 
	WP, 
	COMP, 
	PULSE, 
	WP_RSTN);
   output SAR_REG0;
   output [11:0] WP;
   input COMP;
   input [11:1] PULSE;
   input WP_RSTN;

   // Internal wires
   wire FE_ECON10_n52;
   wire FE_ECON9_data_from_adc0_1;
   wire FE_ECON8_data_from_adc0_2;
   wire FE_ECON7_data_from_adc0_3;
   wire FE_ECON6_data_from_adc0_4;
   wire FE_ECON5_data_from_adc0_5;
   wire FE_ECON4_data_from_adc0_6;
   wire FE_ECON3_data_from_adc0_7;
   wire FE_ECON2_data_from_adc0_8;
   wire FE_ECON1_data_from_adc0_9;
   wire FE_ECON0_data_from_adc0_10;
   wire LOGIC0;

   DLY2HDLLX0 FE_ECOC10_n52 (.A(WP[0]),
	.Q(FE_ECON10_n52));
   DLY2HDLLX0 FE_ECOC9_data_from_adc0_1 (.A(WP[1]),
	.Q(FE_ECON9_data_from_adc0_1));
   DLY2HDLLX0 FE_ECOC8_data_from_adc0_2 (.A(WP[2]),
	.Q(FE_ECON8_data_from_adc0_2));
   DLY2HDLLX0 FE_ECOC7_data_from_adc0_3 (.A(WP[3]),
	.Q(FE_ECON7_data_from_adc0_3));
   DLY2HDLLX0 FE_ECOC6_data_from_adc0_4 (.A(WP[4]),
	.Q(FE_ECON6_data_from_adc0_4));
   DLY2HDLLX0 FE_ECOC5_data_from_adc0_5 (.A(WP[5]),
	.Q(FE_ECON5_data_from_adc0_5));
   DLY2HDLLX0 FE_ECOC4_data_from_adc0_6 (.A(WP[6]),
	.Q(FE_ECON4_data_from_adc0_6));
   DLY2HDLLX0 FE_ECOC3_data_from_adc0_7 (.A(WP[7]),
	.Q(FE_ECON3_data_from_adc0_7));
   DLY2HDLLX0 FE_ECOC2_data_from_adc0_8 (.A(WP[8]),
	.Q(FE_ECON2_data_from_adc0_8));
   DLY2HDLLX0 FE_ECOC1_data_from_adc0_9 (.A(WP[9]),
	.Q(FE_ECON1_data_from_adc0_9));
   DLY2HDLLX0 FE_ECOC0_data_from_adc0_10 (.A(WP[10]),
	.Q(FE_ECON0_data_from_adc0_10));
   DFRRSQHDLLX0 I39 (.C(LOGIC0),
	.D(LOGIC0),
	.Q(WP[0]),
	.RN(WP_RSTN),
	.SN(PULSE[1]));
   DFRRSQHDLLX0 I38 (.C(FE_ECON10_n52),
	.D(COMP),
	.Q(WP[1]),
	.RN(WP_RSTN),
	.SN(PULSE[2]));
   DFRRSQHDLLX0 I37 (.C(FE_ECON9_data_from_adc0_1),
	.D(COMP),
	.Q(WP[2]),
	.RN(WP_RSTN),
	.SN(PULSE[3]));
   DFRRSQHDLLX0 I36 (.C(FE_ECON8_data_from_adc0_2),
	.D(COMP),
	.Q(WP[3]),
	.RN(WP_RSTN),
	.SN(PULSE[4]));
   DFRRSQHDLLX0 I35 (.C(FE_ECON7_data_from_adc0_3),
	.D(COMP),
	.Q(WP[4]),
	.RN(WP_RSTN),
	.SN(PULSE[5]));
   DFRRSQHDLLX0 I34 (.C(FE_ECON6_data_from_adc0_4),
	.D(COMP),
	.Q(WP[5]),
	.RN(WP_RSTN),
	.SN(PULSE[6]));
   DFRRSQHDLLX0 I33 (.C(FE_ECON5_data_from_adc0_5),
	.D(COMP),
	.Q(WP[6]),
	.RN(WP_RSTN),
	.SN(PULSE[7]));
   DFRRSQHDLLX0 I32 (.C(FE_ECON4_data_from_adc0_6),
	.D(COMP),
	.Q(WP[7]),
	.RN(WP_RSTN),
	.SN(PULSE[8]));
   DFRRSQHDLLX0 I31 (.C(FE_ECON3_data_from_adc0_7),
	.D(COMP),
	.Q(WP[8]),
	.RN(WP_RSTN),
	.SN(PULSE[9]));
   DFRRSQHDLLX0 I30 (.C(FE_ECON2_data_from_adc0_8),
	.D(COMP),
	.Q(WP[9]),
	.RN(WP_RSTN),
	.SN(PULSE[10]));
   DFRRSQHDLLX0 I10 (.C(FE_ECON1_data_from_adc0_9),
	.D(COMP),
	.Q(WP[10]),
	.RN(WP_RSTN),
	.SN(PULSE[11]));
   DFRSQHDLLX0 I0 (.C(FE_ECON0_data_from_adc0_10),
	.D(COMP),
	.Q(WP[11]),
	.SN(WP_RSTN));
   LOGIC0DHDLL I41 (.Q(LOGIC0));
   DFRQHDLLX0 I42 (.C(PULSE[1]),
	.D(COMP),
	.Q(SAR_REG0));
endmodule

module sar_adc_logic_12bit_v4_single_input_fs_v2 (
	RSTN, 
	SAMP_analog, 
	DR, 
	SAMP_RATE_MUX, 
	WP_RSTN, 
	PULSE, 
	CLK, 
	CLK_clone1);
   input RSTN;
   output SAMP_analog;
   output DR;
   input [1:0] SAMP_RATE_MUX;
   output WP_RSTN;
   output [11:0] PULSE;
   input CLK;
   input CLK_clone1;

   // Internal wires
   wire FE_PHN13_counter_1;
   wire FE_PHN10_SYNOPSYS_UNCONNECTED_1;
   wire FE_PHN6_SAMP;
   wire FE_PDN0_n58;
   wire CTS_2;
   wire SAMP;
   wire SAMP_2d;
   wire CLKADC;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N57;
   wire n290;
   wire n52;
   wire n53;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n260;
   wire n270;
   wire n280;
   wire n300;
   wire n310;
   wire n320;
   wire n330;
   wire n340;
   wire n350;
   wire n360;
   wire n370;
   wire n38;
   wire [11:0] counter;

   BUHDLLX1 FE_PHC13_counter_1 (.A(counter[1]),
	.Q(FE_PHN13_counter_1));
   DLY1HDLLX1 FE_PHC10_SYNOPSYS_UNCONNECTED_1 (.A(PULSE[0]),
	.Q(FE_PHN10_SYNOPSYS_UNCONNECTED_1));
   DLY1HDLLX1 FE_PHC6_SAMP (.A(SAMP),
	.Q(FE_PHN6_SAMP));
   BUHDLLX1 FE_PDC0_n58 (.A(RSTN),
	.Q(FE_PDN0_n58));
   INHDLLX2 U44 (.A(CLK_clone1),
	.Q(CTS_2));
   SDFFSQHDLLX0 SAMP_reg (.CN(CLK),
	.D(n53),
	.Q(SAMP),
	.SD(n290),
	.SE(n290),
	.SN(RSTN));
   NO3HDLLX4 U68 (.A(SAMP_2d),
	.B(SAMP),
	.C(CTS_2),
	.Q(CLKADC));
   DFRSQHDLLX0 PULSE_reg_11_ (.C(CLKADC),
	.D(FE_PHN10_SYNOPSYS_UNCONNECTED_1),
	.Q(PULSE[11]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_10_ (.C(CLKADC),
	.D(PULSE[11]),
	.Q(PULSE[10]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_9_ (.C(CLKADC),
	.D(PULSE[10]),
	.Q(PULSE[9]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_8_ (.C(CLKADC),
	.D(PULSE[9]),
	.Q(PULSE[8]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_7_ (.C(CLKADC),
	.D(PULSE[8]),
	.Q(PULSE[7]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_6_ (.C(CLKADC),
	.D(PULSE[7]),
	.Q(PULSE[6]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_5_ (.C(CLKADC),
	.D(PULSE[6]),
	.Q(PULSE[5]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_4_ (.C(CLKADC),
	.D(PULSE[5]),
	.Q(PULSE[4]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_3_ (.C(CLKADC),
	.D(PULSE[4]),
	.Q(PULSE[3]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_2_ (.C(CLKADC),
	.D(PULSE[3]),
	.Q(PULSE[2]),
	.SN(WP_RSTN));
   DFRSQHDLLX0 PULSE_reg_1_ (.C(CLKADC),
	.D(PULSE[2]),
	.Q(PULSE[1]),
	.SN(WP_RSTN));
   SDFRRQHDLLX0 counter_reg_0_ (.C(CLK),
	.D(N26),
	.Q(counter[0]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_1_ (.C(CLK),
	.D(N27),
	.Q(counter[1]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_2_ (.C(CLK),
	.D(N28),
	.Q(counter[2]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_3_ (.C(CLK),
	.D(N29),
	.Q(counter[3]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_4_ (.C(CLK),
	.D(N30),
	.Q(counter[4]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_5_ (.C(CLK),
	.D(N31),
	.Q(counter[5]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_6_ (.C(CLK),
	.D(N32),
	.Q(counter[6]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_7_ (.C(CLK),
	.D(N33),
	.Q(counter[7]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_8_ (.C(CLK),
	.D(N34),
	.Q(counter[8]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_9_ (.C(CLK),
	.D(N35),
	.Q(counter[9]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_10_ (.C(CLK),
	.D(N36),
	.Q(counter[10]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 counter_reg_11_ (.C(CLK),
	.D(N37),
	.Q(counter[11]),
	.RN(FE_PDN0_n58),
	.SD(n290),
	.SE(n290));
   SDFRRQHDLLX0 PULSE_reg_0_ (.C(CLKADC),
	.D(PULSE[1]),
	.Q(PULSE[0]),
	.RN(WP_RSTN),
	.SD(n290),
	.SE(n290));
   SDFRSHDLLX0 WP_RSTN_reg (.C(CLK),
	.D(N57),
	.Q(WP_RSTN),
	.SD(n290),
	.SE(n290),
	.SN(FE_PDN0_n58));
   DFFSQHDLLX0 SAMP_2d_reg (.CN(CLK),
	.D(DR),
	.Q(SAMP_2d),
	.SN(RSTN));
   SDFRSQHDLLX0 SAMP_analog_reg (.C(CLK),
	.D(n52),
	.Q(SAMP_analog),
	.SD(n290),
	.SE(n290),
	.SN(RSTN));
   DFFSQHDLLX0 SAMP_1d_reg (.CN(CLK),
	.D(FE_PHN6_SAMP),
	.Q(DR),
	.SN(RSTN));
   LOGIC0LVHDLL U3 (.Q(n290));
   AN211HDLLX0 U4 (.A(n16),
	.B(n370),
	.C(n18),
	.D(n15),
	.Q(N36));
   INHDLLX0 U5 (.A(n340),
	.Q(n15));
   OA211HDLLX0 U6 (.A(counter[4]),
	.B(n360),
	.C(n350),
	.D(n340),
	.Q(N30));
   OA211HDLLX0 U7 (.A(counter[6]),
	.B(n330),
	.C(n320),
	.D(n340),
	.Q(N32));
   NO2HDLLX0 U8 (.A(n16),
	.B(n370),
	.Q(n18));
   NA4I3HDLLX0 U9 (.AN(n300),
	.BN(counter[9]),
	.CN(n11),
	.D(n24),
	.Q(n340));
   NA2HDLLX0 U10 (.A(counter[9]),
	.B(n38),
	.Q(n370));
   NO2HDLLX0 U11 (.A(n24),
	.B(n23),
	.Q(n38));
   NA3HDLLX0 U12 (.A(n280),
	.B(n270),
	.C(n260),
	.Q(n53));
   NO2HDLLX0 U13 (.A(n270),
	.B(n350),
	.Q(n330));
   AN31HDLLX0 U14 (.A(counter[3]),
	.B(counter[2]),
	.C(counter[1]),
	.D(n25),
	.Q(n280));
   INHDLLX0 U15 (.A(n20),
	.Q(n25));
   NO2HDLLX0 U16 (.A(n13),
	.B(n300),
	.Q(n360));
   NO2HDLLX0 U17 (.A(n19),
	.B(N26),
	.Q(n310));
   NO4I3HDLLX0 U18 (.AN(n1),
	.BN(n12),
	.CN(n9),
	.D(counter[6]),
	.Q(n20));
   INHDLLX0 U19 (.A(counter[0]),
	.Q(N26));
   INHDLLX0 U20 (.A(counter[3]),
	.Q(n13));
   NO3HDLLX0 U21 (.A(counter[8]),
	.B(counter[9]),
	.C(counter[10]),
	.Q(n1));
   INHDLLX0 U22 (.A(counter[7]),
	.Q(n12));
   INHDLLX0 U23 (.A(counter[1]),
	.Q(n19));
   INHDLLX0 U24 (.A(counter[11]),
	.Q(n9));
   INHDLLX0 U25 (.A(counter[5]),
	.Q(n270));
   INHDLLX0 U26 (.A(counter[4]),
	.Q(n260));
   INHDLLX0 U27 (.A(counter[10]),
	.Q(n16));
   NA2HDLLX0 U28 (.A(counter[5]),
	.B(counter[4]),
	.Q(n21));
   INHDLLX0 U29 (.A(counter[8]),
	.Q(n24));
   NO2HDLLX0 U30 (.A(counter[3]),
	.B(counter[2]),
	.Q(n22));
   NO3HDLLX0 U31 (.A(n270),
	.B(n260),
	.C(n25),
	.Q(n2));
   NA4HDLLX0 U32 (.A(FE_PHN13_counter_1),
	.B(n22),
	.C(n2),
	.D(N26),
	.Q(N57));
   NA3HDLLX0 U33 (.A(counter[2]),
	.B(counter[1]),
	.C(counter[0]),
	.Q(n300));
   NA2HDLLX0 U34 (.A(counter[4]),
	.B(n360),
	.Q(n350));
   NA2HDLLX0 U35 (.A(counter[6]),
	.B(n330),
	.Q(n320));
   NO2HDLLX0 U36 (.A(n12),
	.B(n320),
	.Q(n14));
   INHDLLX0 U37 (.A(SAMP_RATE_MUX[1]),
	.Q(n7));
   AN222HDLLX0 U38 (.A(counter[3]),
	.B(counter[7]),
	.C(n7),
	.D(n12),
	.E(n13),
	.F(SAMP_RATE_MUX[1]),
	.Q(n3));
   NA3HDLLX0 U39 (.A(SAMP_RATE_MUX[0]),
	.B(n3),
	.C(n260),
	.Q(n5));
   NO3HDLLX0 U40 (.A(SAMP_RATE_MUX[0]),
	.B(n260),
	.C(n13),
	.Q(n6));
   AN31HDLLX0 U41 (.A(SAMP_RATE_MUX[1]),
	.B(n6),
	.C(counter[7]),
	.D(counter[6]),
	.Q(n4));
   AN211HDLLX0 U42 (.A(counter[6]),
	.B(n5),
	.C(counter[10]),
	.D(n4),
	.Q(n10));
   NO6I5HDLLX0 U43 (.AN(counter[10]),
	.BN(n12),
	.CN(n7),
	.DN(n6),
	.EN(counter[6]),
	.F(n9),
	.Q(n8));
   AN32HDLLX0 U45 (.A(n10),
	.B(n270),
	.C(n9),
	.D(counter[5]),
	.E(n8),
	.Q(n11));
   AN211HDLLX0 U46 (.A(n12),
	.B(n320),
	.C(n14),
	.D(n15),
	.Q(N33));
   AN211HDLLX0 U47 (.A(n13),
	.B(n300),
	.C(n360),
	.D(n15),
	.Q(N29));
   AN211HDLLX0 U48 (.A(n270),
	.B(n350),
	.C(n330),
	.D(n15),
	.Q(N31));
   INHDLLX0 U49 (.A(n14),
	.Q(n23));
   ON21HDLLX0 U50 (.A(counter[11]),
	.B(n18),
	.C(n340),
	.Q(n17));
   AN21HDLLX0 U51 (.A(counter[11]),
	.B(n18),
	.C(n17),
	.Q(N37));
   AN21HDLLX0 U52 (.A(n19),
	.B(N26),
	.C(n310),
	.Q(N27));
   ON21HDLLX0 U53 (.A(n22),
	.B(n21),
	.C(n20),
	.Q(n52));
   AN21HDLLX0 U54 (.A(n24),
	.B(n23),
	.C(n38),
	.Q(N34));
   OA21HDLLX0 U55 (.A(counter[2]),
	.B(n310),
	.C(n300),
	.Q(N28));
   OA21HDLLX0 U56 (.A(counter[9]),
	.B(n38),
	.C(n370),
	.Q(N35));
endmodule

module sar_adc_logic_12bit_v4_single_input_v2_x4 (
	D0, 
	D1, 
	D2, 
	D3, 
	DR, 
	SAMP_analog, 
	WP0, 
	WP1, 
	WP2, 
	WP3, 
	COMP, 
	RSTN, 
	SAMP_RATE_MUX, 
	CLK, 
	CLK_clone1);
   output [11:0] D0;
   output [11:0] D1;
   output [11:0] D2;
   output [11:0] D3;
   output DR;
   output SAMP_analog;
   output [11:0] WP0;
   output [11:0] WP1;
   output [11:0] WP2;
   output [11:0] WP3;
   input [3:0] COMP;
   input RSTN;
   input [1:0] SAMP_RATE_MUX;
   input CLK;
   input CLK_clone1;

   // Internal wires
   wire FE_PDN5_PULSE_1;
   wire FE_PDN0_COMP_1;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire WP_RSTN;
   wire n5;
   wire n6;
   wire n51;
   wire SYNOPSYS_UNCONNECTED_1;
   wire [11:1] PULSE;

   BUHDLLX1 FE_PDC5_PULSE_1 (.A(PULSE[1]),
	.Q(FE_PDN5_PULSE_1));
   BUHDLLX1 FE_PDC0_COMP_1 (.A(COMP[1]),
	.Q(FE_PDN0_COMP_1));
   sar_adc_logic_12bit_v4_single_input_conv_v1_0 I0_0_ (.SAR_REG0(D0[0]),
	.WP({ D0[11],
		D0[10],
		D0[9],
		D0[8],
		D0[7],
		D0[6],
		D0[5],
		D0[4],
		D0[3],
		D0[2],
		D0[1],
		n52 }),
	.COMP(COMP[0]),
	.PULSE(PULSE),
	.WP_RSTN(n5));
   sar_adc_logic_12bit_v4_single_input_conv_v1_1 I0_1_ (.SAR_REG0(D1[0]),
	.WP({ D1[11],
		D1[10],
		D1[9],
		D1[8],
		D1[7],
		D1[6],
		D1[5],
		D1[4],
		D1[3],
		D1[2],
		D1[1],
		n53 }),
	.COMP(FE_PDN0_COMP_1),
	.PULSE(PULSE),
	.WP_RSTN(n5));
   sar_adc_logic_12bit_v4_single_input_conv_v1_2 I0_2_ (.SAR_REG0(D2[0]),
	.WP({ D2[11],
		D2[10],
		D2[9],
		D2[8],
		D2[7],
		D2[6],
		D2[5],
		D2[4],
		D2[3],
		D2[2],
		D2[1],
		n54 }),
	.COMP(COMP[2]),
	.PULSE({ PULSE[11],
		PULSE[10],
		PULSE[9],
		PULSE[8],
		PULSE[7],
		PULSE[6],
		PULSE[5],
		PULSE[4],
		PULSE[3],
		PULSE[2],
		FE_PDN5_PULSE_1 }),
	.WP_RSTN(n6));
   sar_adc_logic_12bit_v4_single_input_conv_v1_3 I0_3_ (.SAR_REG0(D3[0]),
	.WP({ D3[11],
		D3[10],
		D3[9],
		D3[8],
		D3[7],
		D3[6],
		D3[5],
		D3[4],
		D3[3],
		D3[2],
		D3[1],
		n55 }),
	.COMP(COMP[3]),
	.PULSE({ PULSE[11],
		PULSE[10],
		PULSE[9],
		PULSE[8],
		PULSE[7],
		PULSE[6],
		PULSE[5],
		PULSE[4],
		PULSE[3],
		PULSE[2],
		FE_PDN5_PULSE_1 }),
	.WP_RSTN(n6));
   sar_adc_logic_12bit_v4_single_input_fs_v2 I1 (.RSTN(RSTN),
	.SAMP_analog(SAMP_analog),
	.DR(DR),
	.SAMP_RATE_MUX(SAMP_RATE_MUX),
	.WP_RSTN(WP_RSTN),
	.PULSE({ PULSE,
		SYNOPSYS_UNCONNECTED_1 }),
	.CLK(CLK),
	.CLK_clone1(CLK_clone1));
   BUHDLLX0 U1 (.A(D3[11]),
	.Q(WP3[11]));
   BUHDLLX0 U2 (.A(D1[11]),
	.Q(WP1[11]));
   BUHDLLX0 U3 (.A(D2[11]),
	.Q(WP2[11]));
   BUHDLLX0 U4 (.A(D0[11]),
	.Q(WP0[11]));
   BUHDLLX0 U5 (.A(D1[10]),
	.Q(WP1[10]));
   BUHDLLX0 U6 (.A(D3[10]),
	.Q(WP3[10]));
   BUHDLLX0 U7 (.A(D2[10]),
	.Q(WP2[10]));
   BUHDLLX0 U8 (.A(D0[10]),
	.Q(WP0[10]));
   BUHDLLX0 U9 (.A(D2[9]),
	.Q(WP2[9]));
   BUHDLLX0 U10 (.A(D0[9]),
	.Q(WP0[9]));
   BUHDLLX0 U11 (.A(D1[9]),
	.Q(WP1[9]));
   BUHDLLX0 U12 (.A(D3[9]),
	.Q(WP3[9]));
   BUHDLLX0 U13 (.A(D0[8]),
	.Q(WP0[8]));
   BUHDLLX0 U14 (.A(D3[8]),
	.Q(WP3[8]));
   BUHDLLX0 U15 (.A(D1[8]),
	.Q(WP1[8]));
   BUHDLLX0 U16 (.A(D2[8]),
	.Q(WP2[8]));
   BUHDLLX0 U17 (.A(D3[7]),
	.Q(WP3[7]));
   BUHDLLX0 U18 (.A(D0[7]),
	.Q(WP0[7]));
   BUHDLLX0 U19 (.A(D2[7]),
	.Q(WP2[7]));
   BUHDLLX0 U20 (.A(D1[7]),
	.Q(WP1[7]));
   BUHDLLX0 U21 (.A(D2[6]),
	.Q(WP2[6]));
   BUHDLLX0 U22 (.A(D1[6]),
	.Q(WP1[6]));
   BUHDLLX0 U23 (.A(D0[6]),
	.Q(WP0[6]));
   BUHDLLX0 U24 (.A(D3[6]),
	.Q(WP3[6]));
   BUHDLLX0 U25 (.A(D0[5]),
	.Q(WP0[5]));
   BUHDLLX0 U26 (.A(D3[5]),
	.Q(WP3[5]));
   BUHDLLX0 U27 (.A(D1[5]),
	.Q(WP1[5]));
   BUHDLLX0 U28 (.A(D2[5]),
	.Q(WP2[5]));
   BUHDLLX0 U29 (.A(D0[4]),
	.Q(WP0[4]));
   BUHDLLX0 U30 (.A(D1[4]),
	.Q(WP1[4]));
   BUHDLLX0 U31 (.A(D2[4]),
	.Q(WP2[4]));
   BUHDLLX0 U32 (.A(D3[4]),
	.Q(WP3[4]));
   BUHDLLX0 U33 (.A(D2[3]),
	.Q(WP2[3]));
   BUHDLLX0 U34 (.A(D1[3]),
	.Q(WP1[3]));
   BUHDLLX0 U35 (.A(D3[3]),
	.Q(WP3[3]));
   BUHDLLX0 U36 (.A(D0[3]),
	.Q(WP0[3]));
   BUHDLLX0 U37 (.A(D1[2]),
	.Q(WP1[2]));
   BUHDLLX0 U38 (.A(D3[2]),
	.Q(WP3[2]));
   BUHDLLX0 U39 (.A(D2[2]),
	.Q(WP2[2]));
   BUHDLLX0 U40 (.A(D0[2]),
	.Q(WP0[2]));
   BUHDLLX0 U41 (.A(D0[1]),
	.Q(WP0[1]));
   BUHDLLX0 U42 (.A(D2[1]),
	.Q(WP2[1]));
   BUHDLLX0 U43 (.A(D1[1]),
	.Q(WP1[1]));
   BUHDLLX0 U44 (.A(D3[1]),
	.Q(WP3[1]));
   INHDLLX0 U45 (.A(WP_RSTN),
	.Q(n51));
   BUHDLLX0 U46 (.A(n55),
	.Q(WP3[0]));
   BUHDLLX0 U47 (.A(n54),
	.Q(WP2[0]));
   BUHDLLX0 U48 (.A(n53),
	.Q(WP1[0]));
   BUHDLLX0 U49 (.A(n52),
	.Q(WP0[0]));
   INHDLLX2 U50 (.A(n51),
	.Q(n5));
   INHDLLX2 U51 (.A(n51),
	.Q(n6));
endmodule

module RST_N_SYN (
	rst_n, 
	rst_syn_n, 
	clk_sys);
   input rst_n;
   output rst_syn_n;
   input clk_sys;

   // Internal wires
   wire FE_PHN12_rst_syn_n_buf;
   wire n_Logic1_;
   wire rst_syn_n_buf;
   wire n2;

   BUHDLLX2 FE_PHC12_rst_syn_n_buf (.A(FE_PHN12_rst_syn_n_buf),
	.Q(rst_syn_n_buf));
   SDFRRQHDLLX0 rst_syn_n_buf_reg (.C(clk_sys),
	.D(n_Logic1_),
	.Q(FE_PHN12_rst_syn_n_buf),
	.RN(rst_n),
	.SD(n2),
	.SE(n2));
   SDFRRQHDLLX0 rst_syn_n_reg (.C(clk_sys),
	.D(rst_syn_n_buf),
	.Q(rst_syn_n),
	.RN(rst_n),
	.SD(n2),
	.SE(n2));
   LOGIC1LVHDLL U3 (.Q(n_Logic1_));
   LOGIC0LVHDLL U4 (.Q(n2));
endmodule

module SNPS_CLOCK_GATE_LOW_FSM_BLOCK (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCNHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_0 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_4 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_3 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_2 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_0_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   LSGCPHDLLX0 latch (.CLK(CLK),
	.E(EN),
	.GCLK(ENCLK),
	.SE(TE));
endmodule

module FSM_BLOCK (
	clk, 
	rst_n, 
	data_in, 
	addr, 
	code, 
	data_out, 
	reg_map_addr, 
	SAMP_RATE_MUX, 
	adc_ready, 
	data_from_adc0, 
	data_from_adc1, 
	data_from_adc2, 
	data_from_adc3, 
	data_from_pre, 
	data_to_post, 
	Rec_0, 
	Rec_1, 
	Rec_2, 
	Rec_3, 
	D_HP, 
	clk_clone1, 
	clk_clone2);
   input clk;
   input rst_n;
   input [15:0] data_in;
   input [9:0] addr;
   input [5:0] code;
   inout [15:0] data_out;
   input [7:0] reg_map_addr;
   output [1:0] SAMP_RATE_MUX;
   input adc_ready;
   input [11:0] data_from_adc0;
   input [11:0] data_from_adc1;
   input [11:0] data_from_adc2;
   input [11:0] data_from_adc3;
   input [12:0] data_from_pre;
   output [12:0] data_to_post;
   output [11:0] Rec_0;
   output [11:0] Rec_1;
   output [11:0] Rec_2;
   output [11:0] Rec_3;
   output [3:0] D_HP;
   input clk_clone1;
   input clk_clone2;

   // Internal wires
   wire FE_PHN11_adc_ready_z_1;
   wire FE_PHN9_adc_ready_z_0;
   wire FE_PHN8_clk_reg_gate_d1;
   wire FE_PHN7_data_out_en_1d;
   wire FE_PDN3_n259;
   wire FE_PDN2_n257;
   wire FE_PDN1_n256;
   wire CTS_6;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire adc_ready_pos;
   wire en_clk_shift_l;
   wire N53;
   wire N54;
   wire N55;
   wire N56;
   wire N57;
   wire N58;
   wire N59;
   wire N65;
   wire N66;
   wire N67;
   wire N68;
   wire N69;
   wire N70;
   wire N71;
   wire N72;
   wire N73;
   wire N74;
   wire N75;
   wire N76;
   wire N77;
   wire clk_reg_gate;
   wire clk_reg_gate_d1;
   wire clk_reg_gate_d2;
   wire clk_reg;
   wire N83;
   wire N90;
   wire N97;
   wire N104;
   wire N107;
   wire clk_data_out_buf_gate;
   wire clk_data_out_buf_gate_trigger;
   wire clk_data_out_buf;
   wire N189;
   wire N190;
   wire N191;
   wire N192;
   wire N193;
   wire N194;
   wire N195;
   wire N196;
   wire N197;
   wire N198;
   wire N199;
   wire N200;
   wire N201;
   wire N202;
   wire N203;
   wire N204;
   wire data_out_en_1d;
   wire N205;
   wire net169;
   wire net174;
   wire net179;
   wire net184;
   wire net189;
   wire n580;
   wire n60;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n1;
   wire n3;
   wire n5;
   wire n7;
   wire n9;
   wire n11;
   wire n13;
   wire n15;
   wire n17;
   wire n19;
   wire n21;
   wire n23;
   wire n25;
   wire n27;
   wire n29;
   wire n31;
   wire n33;
   wire n35;
   wire n37;
   wire n39;
   wire n41;
   wire n43;
   wire n45;
   wire n47;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n530;
   wire n540;
   wire n550;
   wire n560;
   wire n570;
   wire n590;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n650;
   wire n660;
   wire n670;
   wire n680;
   wire n690;
   wire n710;
   wire n730;
   wire n750;
   wire n770;
   wire n79;
   wire n81;
   wire n830;
   wire n85;
   wire n87;
   wire n89;
   wire n91;
   wire n93;
   wire n95;
   wire n970;
   wire n99;
   wire n101;
   wire n103;
   wire n105;
   wire n1070;
   wire n109;
   wire n111;
   wire n113;
   wire n115;
   wire n117;
   wire n119;
   wire n121;
   wire n123;
   wire n125;
   wire n127;
   wire n129;
   wire n131;
   wire n133;
   wire n135;
   wire n137;
   wire n139;
   wire n141;
   wire n143;
   wire n145;
   wire n147;
   wire n149;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n1890;
   wire n1900;
   wire n1910;
   wire n1920;
   wire n1930;
   wire n1940;
   wire n1950;
   wire n1960;
   wire n1970;
   wire n1980;
   wire n1990;
   wire n2000;
   wire n2010;
   wire n2020;
   wire n2030;
   wire n2040;
   wire n2050;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire [2:0] adc_ready_z;
   wire [47:0] data_adc_buffer;
   wire [6:0] block_cnt;
   wire [12:0] data_from_pre_buf;
   wire [15:0] data_out_buf;

   DLY1HDLLX1 FE_PHC11_adc_ready_z_1 (.A(adc_ready_z[1]),
	.Q(FE_PHN11_adc_ready_z_1));
   DLY1HDLLX1 FE_PHC9_adc_ready_z_0 (.A(adc_ready_z[0]),
	.Q(FE_PHN9_adc_ready_z_0));
   DLY1HDLLX1 FE_PHC8_clk_reg_gate_d1 (.A(clk_reg_gate_d1),
	.Q(FE_PHN8_clk_reg_gate_d1));
   DLY1HDLLX1 FE_PHC7_data_out_en_1d (.A(FE_PHN7_data_out_en_1d),
	.Q(data_out_en_1d));
   BUHDLLX1 FE_PDC3_n259 (.A(n259),
	.Q(FE_PDN3_n259));
   BUHDLLX1 FE_PDC2_n257 (.A(n257),
	.Q(FE_PDN2_n257));
   BUHDLLX1 FE_PDC1_n256 (.A(n256),
	.Q(FE_PDN1_n256));
   ANTENNACELLNP2HDLL DIODE_3 (.A(data_adc_buffer[5]));
   ANTENNACELLNP2HDLL DIODE_2 (.A(data_adc_buffer[5]));
   ANTENNACELLNP2HDLL DIODE_1 (.A(data_adc_buffer[20]));
   INHDLLX4 U213 (.A(n355),
	.Q(CTS_6));
   BUHDLLX8 CTS_ccl_a_buf_00003 (.A(CTS_3),
	.Q(CTS_2));
   BUHDLLX2 CTS_cid_buf_00022 (.A(CTS_4),
	.Q(CTS_3));
   SNPS_CLOCK_GATE_LOW_FSM_BLOCK clk_gate_data_adc_buffer_reg_3_ (.CLK(clk),
	.EN(adc_ready_pos),
	.ENCLK(CTS_4),
	.TE(n337));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_0 clk_gate_Rec_0_reg (.CLK(clk_reg),
	.EN(N83),
	.ENCLK(net169),
	.TE(n337));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_4 clk_gate_Rec_1_reg (.CLK(clk_reg),
	.EN(N90),
	.ENCLK(net174),
	.TE(n337));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_3 clk_gate_Rec_2_reg (.CLK(clk_reg),
	.EN(N97),
	.ENCLK(net179),
	.TE(n337));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_2 clk_gate_Rec_3_reg (.CLK(clk_reg),
	.EN(N104),
	.ENCLK(net184),
	.TE(n337));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_1 clk_gate_D_HP_reg (.CLK(clk_reg),
	.EN(N107),
	.ENCLK(net189),
	.TE(n337));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__11_ (.CN(CTS_2),
	.D(data_from_adc3[11]),
	.Q(data_adc_buffer[47]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__10_ (.CN(CTS_2),
	.D(data_from_adc3[10]),
	.Q(data_adc_buffer[46]),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__9_ (.CN(CTS_2),
	.D(data_from_adc3[9]),
	.Q(data_adc_buffer[45]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__8_ (.CN(CTS_2),
	.D(data_from_adc3[8]),
	.Q(data_adc_buffer[44]),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__7_ (.CN(CTS_2),
	.D(data_from_adc3[7]),
	.Q(data_adc_buffer[43]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__6_ (.CN(CTS_2),
	.D(data_from_adc3[6]),
	.Q(data_adc_buffer[42]),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__5_ (.CN(CTS_2),
	.D(data_from_adc3[5]),
	.Q(data_adc_buffer[41]),
	.SD(n337),
	.SE(n337),
	.SN(rst_n));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__4_ (.CN(CTS_2),
	.D(data_from_adc3[4]),
	.Q(data_adc_buffer[40]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__3_ (.CN(CTS_2),
	.D(data_from_adc3[3]),
	.Q(data_adc_buffer[39]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__2_ (.CN(CTS_2),
	.D(data_from_adc3[2]),
	.Q(data_adc_buffer[38]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__1_ (.CN(CTS_2),
	.D(data_from_adc3[1]),
	.Q(data_adc_buffer[37]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_3__0_ (.CN(CTS_2),
	.D(data_from_adc3[0]),
	.Q(data_adc_buffer[36]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__11_ (.CN(CTS_2),
	.D(data_from_adc2[11]),
	.Q(data_adc_buffer[35]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__10_ (.CN(CTS_2),
	.D(data_from_adc2[10]),
	.Q(data_adc_buffer[34]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__9_ (.CN(CTS_2),
	.D(data_from_adc2[9]),
	.Q(data_adc_buffer[33]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__8_ (.CN(CTS_2),
	.D(data_from_adc2[8]),
	.Q(data_adc_buffer[32]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__7_ (.CN(CTS_2),
	.D(data_from_adc2[7]),
	.Q(data_adc_buffer[31]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__6_ (.CN(CTS_2),
	.D(data_from_adc2[6]),
	.Q(data_adc_buffer[30]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__5_ (.CN(CTS_2),
	.D(data_from_adc2[5]),
	.Q(data_adc_buffer[29]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__4_ (.CN(CTS_2),
	.D(data_from_adc2[4]),
	.Q(data_adc_buffer[28]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__3_ (.CN(CTS_2),
	.D(data_from_adc2[3]),
	.Q(data_adc_buffer[27]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__2_ (.CN(CTS_2),
	.D(data_from_adc2[2]),
	.Q(data_adc_buffer[26]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__1_ (.CN(CTS_2),
	.D(data_from_adc2[1]),
	.Q(data_adc_buffer[25]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_2__0_ (.CN(CTS_2),
	.D(data_from_adc2[0]),
	.Q(data_adc_buffer[24]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSHDLLX0 data_adc_buffer_reg_1__11_ (.CN(CTS_2),
	.D(data_from_adc1[11]),
	.Q(data_adc_buffer[23]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__10_ (.CN(CTS_2),
	.D(data_from_adc1[10]),
	.Q(data_adc_buffer[22]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__9_ (.CN(CTS_2),
	.D(data_from_adc1[9]),
	.Q(data_adc_buffer[21]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__8_ (.CN(CTS_2),
	.D(data_from_adc1[8]),
	.Q(data_adc_buffer[20]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__7_ (.CN(CTS_2),
	.D(data_from_adc1[7]),
	.Q(data_adc_buffer[19]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__6_ (.CN(CTS_2),
	.D(data_from_adc1[6]),
	.Q(data_adc_buffer[18]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__5_ (.CN(CTS_2),
	.D(data_from_adc1[5]),
	.Q(data_adc_buffer[17]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__4_ (.CN(CTS_2),
	.D(data_from_adc1[4]),
	.Q(data_adc_buffer[16]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__3_ (.CN(CTS_2),
	.D(data_from_adc1[3]),
	.Q(data_adc_buffer[15]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__2_ (.CN(CTS_2),
	.D(data_from_adc1[2]),
	.Q(data_adc_buffer[14]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__1_ (.CN(CTS_2),
	.D(data_from_adc1[1]),
	.Q(data_adc_buffer[13]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSHDLLX0 data_adc_buffer_reg_1__0_ (.CN(CTS_2),
	.D(data_from_adc1[0]),
	.Q(data_adc_buffer[12]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__11_ (.CN(CTS_2),
	.D(data_from_adc0[11]),
	.Q(data_adc_buffer[11]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__10_ (.CN(CTS_2),
	.D(data_from_adc0[10]),
	.Q(data_adc_buffer[10]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__9_ (.CN(CTS_2),
	.D(data_from_adc0[9]),
	.Q(data_adc_buffer[9]),
	.SD(n337),
	.SE(n337),
	.SN(n328));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__8_ (.CN(CTS_2),
	.D(data_from_adc0[8]),
	.Q(data_adc_buffer[8]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__7_ (.CN(CTS_2),
	.D(data_from_adc0[7]),
	.Q(data_adc_buffer[7]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__6_ (.CN(CTS_2),
	.D(data_from_adc0[6]),
	.Q(data_adc_buffer[6]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__5_ (.CN(CTS_2),
	.D(data_from_adc0[5]),
	.Q(data_adc_buffer[5]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__4_ (.CN(CTS_2),
	.D(data_from_adc0[4]),
	.Q(data_adc_buffer[4]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__3_ (.CN(CTS_2),
	.D(data_from_adc0[3]),
	.Q(data_adc_buffer[3]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__2_ (.CN(CTS_2),
	.D(data_from_adc0[2]),
	.Q(data_adc_buffer[2]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__1_ (.CN(CTS_2),
	.D(data_from_adc0[1]),
	.Q(data_adc_buffer[1]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFFSQHDLLX0 data_adc_buffer_reg_0__0_ (.CN(CTS_2),
	.D(data_from_adc0[0]),
	.Q(data_adc_buffer[0]),
	.SD(n337),
	.SE(n337),
	.SN(n329));
   SDFRSHDLLX0 block_cnt_reg_0_ (.C(CTS_6),
	.D(N53),
	.Q(block_cnt[0]),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFFRQHDLLX0 en_clk_shift_l_reg (.CN(clk_clone1),
	.D(n354),
	.Q(en_clk_shift_l),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFRSQHDLLX0 block_cnt_reg_6_ (.C(CTS_6),
	.D(N59),
	.Q(block_cnt[6]),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 block_cnt_reg_5_ (.C(CTS_6),
	.D(N58),
	.Q(block_cnt[5]),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSHDLLX0 block_cnt_reg_4_ (.C(CTS_6),
	.D(N57),
	.Q(block_cnt[4]),
	.QN(n326),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFRSHDLLX0 block_cnt_reg_3_ (.C(CTS_6),
	.D(N56),
	.Q(block_cnt[3]),
	.QN(n327),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFRSQHDLLX0 block_cnt_reg_2_ (.C(CTS_6),
	.D(N55),
	.Q(block_cnt[2]),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 block_cnt_reg_1_ (.C(CTS_6),
	.D(N54),
	.Q(block_cnt[1]),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFFSQHDLLX0 data_from_pre_buf_reg_12_ (.CN(CTS_6),
	.D(data_from_pre[12]),
	.Q(data_from_pre_buf[12]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_11_ (.CN(CTS_6),
	.D(data_from_pre[11]),
	.Q(data_from_pre_buf[11]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_10_ (.CN(CTS_6),
	.D(data_from_pre[10]),
	.Q(data_from_pre_buf[10]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_9_ (.CN(CTS_6),
	.D(data_from_pre[9]),
	.Q(data_from_pre_buf[9]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_8_ (.CN(CTS_6),
	.D(data_from_pre[8]),
	.Q(data_from_pre_buf[8]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_7_ (.CN(CTS_6),
	.D(data_from_pre[7]),
	.Q(data_from_pre_buf[7]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_6_ (.CN(CTS_6),
	.D(data_from_pre[6]),
	.Q(data_from_pre_buf[6]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_5_ (.CN(CTS_6),
	.D(data_from_pre[5]),
	.Q(data_from_pre_buf[5]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_4_ (.CN(CTS_6),
	.D(data_from_pre[4]),
	.Q(data_from_pre_buf[4]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_3_ (.CN(CTS_6),
	.D(data_from_pre[3]),
	.Q(data_from_pre_buf[3]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_2_ (.CN(CTS_6),
	.D(data_from_pre[2]),
	.Q(data_from_pre_buf[2]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_1_ (.CN(CTS_6),
	.D(data_from_pre[1]),
	.Q(data_from_pre_buf[1]),
	.SD(n337),
	.SE(n337),
	.SN(n330));
   SDFFSQHDLLX0 data_from_pre_buf_reg_0_ (.CN(CTS_6),
	.D(data_from_pre[0]),
	.Q(data_from_pre_buf[0]),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFFRQHDLLX0 clk_reg_gate_d1_reg (.CN(clk_clone1),
	.D(clk_reg_gate),
	.Q(clk_reg_gate_d1),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFRSQHDLLX0 Rec_0_reg_6_ (.C(net169),
	.D(data_in[6]),
	.Q(n363),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_0_reg_5_ (.C(net169),
	.D(data_in[5]),
	.Q(n364),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_0_reg_4_ (.C(net169),
	.D(data_in[4]),
	.Q(n365),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 Rec_0_reg_3_ (.C(net169),
	.D(data_in[3]),
	.Q(n366),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_0_reg_2_ (.C(net169),
	.D(data_in[2]),
	.Q(n367),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 Rec_0_reg_1_ (.C(net169),
	.D(data_in[1]),
	.Q(n368),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_6_ (.C(net174),
	.D(data_in[6]),
	.Q(n375),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_5_ (.C(net174),
	.D(data_in[5]),
	.Q(n376),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_4_ (.C(net174),
	.D(data_in[4]),
	.Q(n377),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_3_ (.C(net174),
	.D(data_in[3]),
	.Q(n378),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_2_ (.C(net174),
	.D(data_in[2]),
	.Q(n379),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_1_reg_1_ (.C(net174),
	.D(data_in[1]),
	.Q(n380),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_2_reg_6_ (.C(net179),
	.D(data_in[6]),
	.Q(n387),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_2_reg_5_ (.C(net179),
	.D(data_in[5]),
	.Q(n388),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_2_reg_4_ (.C(net179),
	.D(data_in[4]),
	.Q(n389),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_2_reg_3_ (.C(net179),
	.D(data_in[3]),
	.Q(n390),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_2_reg_2_ (.C(net179),
	.D(data_in[2]),
	.Q(n391),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_2_reg_1_ (.C(net179),
	.D(data_in[1]),
	.Q(n392),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_3_reg_6_ (.C(net184),
	.D(data_in[6]),
	.Q(n399),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_3_reg_5_ (.C(net184),
	.D(data_in[5]),
	.Q(n400),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_3_reg_4_ (.C(net184),
	.D(data_in[4]),
	.Q(n401),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_3_reg_3_ (.C(net184),
	.D(data_in[3]),
	.Q(n402),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 Rec_3_reg_2_ (.C(net184),
	.D(data_in[2]),
	.Q(n403),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 Rec_3_reg_1_ (.C(net184),
	.D(data_in[1]),
	.Q(n404),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 SAMP_RATE_MUX_reg_1_ (.C(n336),
	.D(n60),
	.Q(SAMP_RATE_MUX[1]),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFRSQHDLLX0 SAMP_RATE_MUX_reg_0_ (.C(n336),
	.D(n580),
	.Q(SAMP_RATE_MUX[0]),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 D_HP_reg_3_ (.C(net189),
	.D(data_in[3]),
	.Q(n406),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 D_HP_reg_2_ (.C(net189),
	.D(data_in[2]),
	.Q(n407),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFRSQHDLLX0 D_HP_reg_1_ (.C(net189),
	.D(data_in[1]),
	.Q(n408),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFRSQHDLLX0 D_HP_reg_0_ (.C(net189),
	.D(data_in[0]),
	.Q(n409),
	.SD(n337),
	.SE(n337),
	.SN(n335));
   SDFFRQHDLLX0 clk_data_out_buf_gate_trigger_reg (.CN(clk_clone1),
	.D(clk_data_out_buf_gate),
	.Q(clk_data_out_buf_gate_trigger),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFFRQHDLLX0 data_out_en_1d_reg (.CN(clk_clone1),
	.D(N205),
	.Q(FE_PHN7_data_out_en_1d),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   AND2HDLLX2 U354 (.A(clk_data_out_buf_gate_trigger),
	.B(clk_clone2),
	.Q(clk_data_out_buf));
   SNPS_CLOCK_GATE_HIGH_FSM_BLOCK_0_1 clk_gate_SAMP_RATE_MUX_reg (.CLK(clk_reg),
	.EN(n338),
	.ENCLK(n336),
	.TE(n337));
   DFFRHDLLX0 data_out_en_2d_reg (.CN(clk_clone1),
	.D(data_out_en_1d),
	.Q(n153),
	.QN(n152),
	.RN(n335));
   DFFRQHDLLX0 clk_reg_gate_d2_reg (.CN(clk_clone1),
	.D(FE_PHN8_clk_reg_gate_d1),
	.Q(clk_reg_gate_d2),
	.RN(n329));
   DFRRQHDLLX0 adc_ready_z_reg_1_ (.C(clk_clone1),
	.D(FE_PHN9_adc_ready_z_0),
	.Q(adc_ready_z[1]),
	.RN(n335));
   DFRRQHDLLX0 adc_ready_z_reg_2_ (.C(clk_clone1),
	.D(FE_PHN11_adc_ready_z_1),
	.Q(adc_ready_z[2]),
	.RN(n335));
   SDFRRQHDLLX0 Rec_0_reg_10_ (.C(net169),
	.D(data_in[10]),
	.Q(n359),
	.RN(n332),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_0_reg_9_ (.C(net169),
	.D(data_in[9]),
	.Q(n360),
	.RN(n328),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_0_reg_8_ (.C(net169),
	.D(data_in[8]),
	.Q(n361),
	.RN(n330),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_0_reg_7_ (.C(net169),
	.D(data_in[7]),
	.Q(n362),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_0_reg_0_ (.C(net169),
	.D(data_in[0]),
	.Q(n369),
	.RN(n329),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_10_ (.C(net174),
	.D(data_in[10]),
	.Q(n371),
	.RN(n328),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_9_ (.C(net174),
	.D(data_in[9]),
	.Q(n372),
	.RN(n334),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_8_ (.C(net174),
	.D(data_in[8]),
	.Q(n373),
	.RN(n330),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_7_ (.C(net174),
	.D(data_in[7]),
	.Q(n374),
	.RN(n332),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_0_ (.C(net174),
	.D(data_in[0]),
	.Q(n381),
	.RN(n333),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_10_ (.C(net179),
	.D(data_in[10]),
	.Q(n383),
	.RN(n331),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_9_ (.C(net179),
	.D(data_in[9]),
	.Q(n384),
	.RN(n331),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_8_ (.C(net179),
	.D(data_in[8]),
	.Q(n385),
	.RN(n329),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_7_ (.C(net179),
	.D(data_in[7]),
	.Q(n386),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_0_ (.C(net179),
	.D(data_in[0]),
	.Q(n393),
	.RN(n330),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_10_ (.C(net184),
	.D(data_in[10]),
	.Q(n395),
	.RN(n329),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_9_ (.C(net184),
	.D(data_in[9]),
	.Q(n396),
	.RN(n328),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_8_ (.C(net184),
	.D(data_in[8]),
	.Q(n397),
	.RN(n333),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_7_ (.C(net184),
	.D(data_in[7]),
	.Q(n398),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_0_ (.C(net184),
	.D(data_in[0]),
	.Q(n405),
	.RN(n328),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_0_reg_11_ (.C(n336),
	.D(n353),
	.Q(n358),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_1_reg_11_ (.C(n336),
	.D(n352),
	.Q(n370),
	.RN(rst_n),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_2_reg_11_ (.C(n336),
	.D(n351),
	.Q(n382),
	.RN(n331),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 Rec_3_reg_11_ (.C(n336),
	.D(n350),
	.Q(n394),
	.RN(n333),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 adc_ready_z_reg_0_ (.C(clk_clone1),
	.D(adc_ready),
	.Q(adc_ready_z[0]),
	.RN(n332),
	.SD(n337),
	.SE(n337));
   SDFRSQHDLLX0 data_to_post_reg_12_ (.C(CTS_6),
	.D(N77),
	.Q(n339),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_11_ (.C(CTS_6),
	.D(N76),
	.Q(n340),
	.SD(n337),
	.SE(n337),
	.SN(n331));
   SDFRSQHDLLX0 data_to_post_reg_10_ (.C(CTS_6),
	.D(N75),
	.Q(n341),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_9_ (.C(CTS_6),
	.D(N74),
	.Q(n342),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_8_ (.C(CTS_6),
	.D(N73),
	.Q(n343),
	.SD(n337),
	.SE(n337),
	.SN(n334));
   SDFRSQHDLLX0 data_to_post_reg_7_ (.C(CTS_6),
	.D(N72),
	.Q(n344),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_6_ (.C(CTS_6),
	.D(N71),
	.Q(n345),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_5_ (.C(CTS_6),
	.D(N70),
	.Q(n346),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_4_ (.C(CTS_6),
	.D(N69),
	.Q(n347),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_3_ (.C(CTS_6),
	.D(N68),
	.Q(n348),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRSQHDLLX0 data_to_post_reg_2_ (.C(CTS_6),
	.D(N67),
	.Q(n349),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_1_ (.C(CTS_6),
	.D(N66),
	.Q(n356),
	.SD(n337),
	.SE(n337),
	.SN(n332));
   SDFRSQHDLLX0 data_to_post_reg_0_ (.C(CTS_6),
	.D(N65),
	.Q(n357),
	.SD(n337),
	.SE(n337),
	.SN(n333));
   SDFRRQHDLLX0 data_out_buf_reg_15_ (.C(clk_data_out_buf),
	.D(N204),
	.Q(data_out_buf[15]),
	.RN(n334),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_14_ (.C(clk_data_out_buf),
	.D(N203),
	.Q(data_out_buf[14]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_13_ (.C(clk_data_out_buf),
	.D(N202),
	.Q(data_out_buf[13]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_12_ (.C(clk_data_out_buf),
	.D(N201),
	.Q(data_out_buf[12]),
	.RN(n332),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_11_ (.C(clk_data_out_buf),
	.D(N200),
	.Q(data_out_buf[11]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_10_ (.C(clk_data_out_buf),
	.D(N199),
	.Q(data_out_buf[10]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_9_ (.C(clk_data_out_buf),
	.D(N198),
	.Q(data_out_buf[9]),
	.RN(n334),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_8_ (.C(clk_data_out_buf),
	.D(N197),
	.Q(data_out_buf[8]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_7_ (.C(clk_data_out_buf),
	.D(N196),
	.Q(data_out_buf[7]),
	.RN(n330),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_6_ (.C(clk_data_out_buf),
	.D(N195),
	.Q(data_out_buf[6]),
	.RN(n329),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_5_ (.C(clk_data_out_buf),
	.D(N194),
	.Q(data_out_buf[5]),
	.RN(n328),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_4_ (.C(clk_data_out_buf),
	.D(N193),
	.Q(data_out_buf[4]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_3_ (.C(clk_data_out_buf),
	.D(N192),
	.Q(data_out_buf[3]),
	.RN(n331),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_2_ (.C(clk_data_out_buf),
	.D(N191),
	.Q(data_out_buf[2]),
	.RN(n333),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_1_ (.C(clk_data_out_buf),
	.D(N190),
	.Q(data_out_buf[1]),
	.RN(n334),
	.SD(n337),
	.SE(n337));
   SDFRRQHDLLX0 data_out_buf_reg_0_ (.C(clk_data_out_buf),
	.D(N189),
	.Q(data_out_buf[0]),
	.RN(n335),
	.SD(n337),
	.SE(n337));
   NA2HDLLX2 U212 (.A(en_clk_shift_l),
	.B(clk_clone2),
	.Q(n355));
   LOGIC0LVHDLL U3 (.Q(n337));
   ON211HDLLX0 U4 (.A(n293),
	.B(n318),
	.C(n292),
	.D(n291),
	.Q(N69));
   ON211HDLLX0 U5 (.A(n311),
	.B(n318),
	.C(n310),
	.D(n309),
	.Q(N75));
   NA4HDLLX0 U6 (.A(n239),
	.B(n238),
	.C(n237),
	.D(n236),
	.Q(N193));
   NA4HDLLX0 U7 (.A(n231),
	.B(n230),
	.C(n229),
	.D(n228),
	.Q(N198));
   NA4HDLLX0 U8 (.A(n227),
	.B(n226),
	.C(n225),
	.D(n224),
	.Q(N197));
   ON211HDLLX0 U9 (.A(n290),
	.B(n289),
	.C(n288),
	.D(n287),
	.Q(N68));
   ON211HDLLX0 U10 (.A(n279),
	.B(n318),
	.C(n278),
	.D(n277),
	.Q(N65));
   NA4HDLLX0 U11 (.A(n263),
	.B(n262),
	.C(n261),
	.D(n260),
	.Q(N196));
   NA4HDLLX0 U12 (.A(n247),
	.B(n246),
	.C(n245),
	.D(n244),
	.Q(N200));
   NA4HDLLX0 U13 (.A(n251),
	.B(n250),
	.C(n249),
	.D(n248),
	.Q(N199));
   ON211HDLLX0 U14 (.A(n302),
	.B(n318),
	.C(n301),
	.D(n300),
	.Q(N72));
   NA4HDLLX0 U15 (.A(n243),
	.B(n242),
	.C(n241),
	.D(n240),
	.Q(N194));
   NA4HDLLX0 U16 (.A(n235),
	.B(n234),
	.C(n233),
	.D(n232),
	.Q(N195));
   ON211HDLLX0 U17 (.A(n305),
	.B(n318),
	.C(n304),
	.D(n303),
	.Q(N73));
   ON211HDLLX0 U18 (.A(n319),
	.B(n318),
	.C(n317),
	.D(n316),
	.Q(N76));
   ON211HDLLX0 U19 (.A(n299),
	.B(n318),
	.C(n298),
	.D(n297),
	.Q(N71));
   ON211HDLLX0 U20 (.A(n282),
	.B(n318),
	.C(n281),
	.D(n280),
	.Q(N66));
   ON211HDLLX0 U21 (.A(n308),
	.B(n318),
	.C(n307),
	.D(n306),
	.Q(N74));
   ON211HDLLX0 U22 (.A(n296),
	.B(n318),
	.C(n295),
	.D(n294),
	.Q(N70));
   ON211HDLLX0 U23 (.A(n285),
	.B(n289),
	.C(n284),
	.D(n283),
	.Q(N67));
   AN22HDLLX0 U24 (.A(data_adc_buffer[13]),
	.B(n313),
	.C(data_from_pre_buf[1]),
	.D(n312),
	.Q(n281));
   AN22HDLLX0 U25 (.A(n253),
	.B(n364),
	.C(n252),
	.D(n388),
	.Q(n231));
   INHDLLX0 U26 (.A(n286),
	.Q(n318));
   AN22HDLLX0 U27 (.A(n253),
	.B(n365),
	.C(n252),
	.D(n389),
	.Q(n227));
   AN22HDLLX0 U28 (.A(n255),
	.B(n378),
	.C(n254),
	.D(n402),
	.Q(n262));
   AN22HDLLX0 U29 (.A(n255),
	.B(n375),
	.C(n254),
	.D(n399),
	.Q(n250));
   AN22HDLLX0 U30 (.A(n253),
	.B(n362),
	.C(n252),
	.D(n386),
	.Q(n247));
   AN22HDLLX0 U31 (.A(n255),
	.B(n379),
	.C(n254),
	.D(n403),
	.Q(n234));
   AN22HDLLX0 U32 (.A(n253),
	.B(n367),
	.C(n252),
	.D(n391),
	.Q(n235));
   AN22HDLLX0 U33 (.A(data_adc_buffer[12]),
	.B(n313),
	.C(data_from_pre_buf[0]),
	.D(n312),
	.Q(n278));
   AN22HDLLX0 U34 (.A(n255),
	.B(n376),
	.C(n254),
	.D(n400),
	.Q(n230));
   AN22HDLLX0 U35 (.A(n255),
	.B(n377),
	.C(n254),
	.D(n401),
	.Q(n226));
   AN22HDLLX0 U36 (.A(n253),
	.B(n363),
	.C(n252),
	.D(n387),
	.Q(n251));
   AN22HDLLX0 U37 (.A(n255),
	.B(n380),
	.C(n254),
	.D(n404),
	.Q(n242));
   AN22HDLLX0 U38 (.A(n255),
	.B(n374),
	.C(n254),
	.D(n398),
	.Q(n246));
   AN22HDLLX0 U39 (.A(n253),
	.B(n368),
	.C(n252),
	.D(n392),
	.Q(n243));
   AN22HDLLX0 U40 (.A(n253),
	.B(n366),
	.C(n252),
	.D(n390),
	.Q(n263));
   NA3HDLLX0 U41 (.A(n1960),
	.B(n1950),
	.C(n1940),
	.Q(N189));
   ON211HDLLX0 U42 (.A(n206),
	.B(n290),
	.C(n2050),
	.D(n2040),
	.Q(N192));
   AN22HDLLX0 U43 (.A(n253),
	.B(n369),
	.C(n252),
	.D(n393),
	.Q(n239));
   ON211HDLLX0 U44 (.A(n206),
	.B(n285),
	.C(n2020),
	.D(n2010),
	.Q(N191));
   AN22HDLLX0 U45 (.A(n255),
	.B(n381),
	.C(n254),
	.D(n405),
	.Q(n238));
   NA3HDLLX0 U46 (.A(n2000),
	.B(n1990),
	.C(n1980),
	.Q(N190));
   NO2HDLLX0 U47 (.A(n188),
	.B(n187),
	.Q(n323));
   NO2HDLLX1 U48 (.A(n166),
	.B(n1900),
	.Q(n255));
   NO2HDLLX1 U49 (.A(n1920),
	.B(n166),
	.Q(n254));
   NO3HDLLX1 U50 (.A(addr[1]),
	.B(addr[0]),
	.C(n166),
	.Q(n253));
   NO2HDLLX1 U51 (.A(n1910),
	.B(n166),
	.Q(n252));
   INHDLLX0 U52 (.A(n289),
	.Q(n315));
   INHDLLX0 U53 (.A(n256),
	.Q(n206));
   NO3HDLLX1 U54 (.A(block_cnt[3]),
	.B(n326),
	.C(n312),
	.Q(n314));
   NO3HDLLX1 U55 (.A(block_cnt[4]),
	.B(n327),
	.C(n312),
	.Q(n313));
   NA2HDLLX0 U56 (.A(n266),
	.B(n273),
	.Q(n354));
   INHDLLX0 U57 (.A(n2030),
	.Q(n166));
   NO2I1HDLLX0 U58 (.AN(data_from_pre_buf[12]),
	.B(n276),
	.Q(N77));
   NO2HDLLX1 U59 (.A(n1930),
	.B(n1900),
	.Q(n258));
   NO3HDLLX0 U60 (.A(addr[1]),
	.B(addr[0]),
	.C(n1930),
	.Q(n256));
   NO2HDLLX0 U61 (.A(n1930),
	.B(n1920),
	.Q(n259));
   ON211HDLLX0 U62 (.A(n216),
	.B(n215),
	.C(n214),
	.D(n213),
	.Q(clk_reg_gate));
   NO2HDLLX0 U63 (.A(n1910),
	.B(n1930),
	.Q(n257));
   NA3HDLLX0 U64 (.A(n327),
	.B(n326),
	.C(n276),
	.Q(n289));
   INHDLLX0 U65 (.A(n276),
	.Q(n312));
   ON21HDLLX0 U66 (.A(n265),
	.B(n275),
	.C(en_clk_shift_l),
	.Q(n266));
   NO2HDLLX0 U67 (.A(n1890),
	.B(n1970),
	.Q(n269));
   NO2HDLLX0 U68 (.A(n165),
	.B(n164),
	.Q(N107));
   NO2HDLLX0 U69 (.A(n175),
	.B(n271),
	.Q(n1890));
   NO2HDLLX0 U70 (.A(n175),
	.B(n217),
	.Q(n1970));
   NA3I2HDLLX0 U71 (.AN(block_cnt[1]),
	.BN(block_cnt[6]),
	.C(n264),
	.Q(n275));
   NA2I1HDLLX0 U72 (.AN(n175),
	.B(n209),
	.Q(n165));
   OA211HDLLX0 U73 (.A(block_cnt[1]),
	.B(block_cnt[0]),
	.C(n272),
	.D(n273),
	.Q(N54));
   INHDLLX0 U74 (.A(n210),
	.Q(n211));
   AN31HDLLX0 U75 (.A(n267),
	.B(code[0]),
	.C(n176),
	.D(n178),
	.Q(n214));
   INHDLLX0 U76 (.A(n345),
	.Q(n137));
   NA4HDLLX0 U77 (.A(n268),
	.B(n209),
	.C(n176),
	.D(n221),
	.Q(n210));
   NA4HDLLX0 U78 (.A(block_cnt[5]),
	.B(block_cnt[0]),
	.C(n327),
	.D(n326),
	.Q(n265));
   INHDLLX0 U79 (.A(n324),
	.Q(n325));
   INHDLLX0 U80 (.A(n341),
	.Q(n129));
   NA3I2HDLLX0 U81 (.AN(code[5]),
	.BN(n221),
	.C(n268),
	.Q(n175));
   INHDLLX0 U82 (.A(n346),
	.Q(n139));
   INHDLLX0 U83 (.A(n349),
	.Q(n145));
   INHDLLX0 U84 (.A(n339),
	.Q(n125));
   INHDLLX0 U85 (.A(n347),
	.Q(n141));
   INHDLLX0 U86 (.A(n357),
	.Q(n149));
   INHDLLX0 U87 (.A(n344),
	.Q(n135));
   NO2HDLLX0 U88 (.A(block_cnt[0]),
	.B(adc_ready_pos),
	.Q(N53));
   INHDLLX0 U89 (.A(n343),
	.Q(n133));
   INHDLLX0 U90 (.A(n342),
	.Q(n131));
   INHDLLX0 U91 (.A(n356),
	.Q(n147));
   INHDLLX0 U92 (.A(n348),
	.Q(n143));
   INHDLLX0 U93 (.A(n340),
	.Q(n127));
   NA2HDLLX0 U94 (.A(n268),
	.B(n267),
	.Q(n270));
   INHDLLX0 U95 (.A(block_cnt[2]),
	.Q(n264));
   INHDLLX0 U96 (.A(data_out_buf[15]),
	.Q(n151));
   INHDLLX0 U97 (.A(data_out_buf[6]),
	.Q(n61));
   INHDLLX0 U98 (.A(data_out_buf[13]),
	.Q(n49));
   INHDLLX0 U99 (.A(data_out_buf[14]),
	.Q(n51));
   NO2HDLLX0 U100 (.A(n163),
	.B(n162),
	.Q(n268));
   INHDLLX0 U101 (.A(n178),
	.Q(n185));
   INHDLLX0 U102 (.A(data_out_buf[7]),
	.Q(n590));
   INHDLLX0 U103 (.A(data_out_buf[12]),
	.Q(n530));
   INHDLLX0 U104 (.A(data_out_buf[8]),
	.Q(n570));
   INHDLLX0 U105 (.A(data_out_buf[11]),
	.Q(n540));
   INHDLLX0 U106 (.A(data_out_buf[9]),
	.Q(n560));
   INHDLLX0 U107 (.A(data_out_buf[10]),
	.Q(n550));
   INHDLLX0 U108 (.A(data_out_buf[0]),
	.Q(n680));
   INHDLLX0 U109 (.A(data_out_buf[1]),
	.Q(n670));
   INHDLLX0 U110 (.A(data_out_buf[2]),
	.Q(n650));
   INHDLLX0 U111 (.A(data_out_buf[3]),
	.Q(n64));
   INHDLLX0 U112 (.A(data_out_buf[5]),
	.Q(n62));
   INHDLLX0 U113 (.A(data_out_buf[4]),
	.Q(n63));
   NO4I3HDLLX0 U114 (.AN(code[3]),
	.BN(n209),
	.CN(n208),
	.D(code[2]),
	.Q(n178));
   AND2HDLLX0 U115 (.A(n209),
	.B(n271),
	.Q(n219));
   NA3HDLLX0 U116 (.A(code[2]),
	.B(code[3]),
	.C(n267),
	.Q(n217));
   NA4HDLLX0 U117 (.A(n161),
	.B(n160),
	.C(n159),
	.D(n158),
	.Q(n162));
   NA4HDLLX0 U118 (.A(n157),
	.B(n156),
	.C(n155),
	.D(n154),
	.Q(n163));
   INHDLLX0 U119 (.A(n273),
	.Q(adc_ready_pos));
   INHDLLX0 U120 (.A(data_adc_buffer[3]),
	.Q(n290));
   INHDLLX0 U121 (.A(data_adc_buffer[2]),
	.Q(n285));
   INHDLLX0 U122 (.A(code[0]),
	.Q(n221));
   NO2I1HDLLX0 U123 (.AN(code[1]),
	.B(code[4]),
	.Q(n267));
   NO2HDLLX0 U124 (.A(code[4]),
	.B(code[1]),
	.Q(n209));
   OR2HDLLX0 U125 (.A(code[2]),
	.B(code[3]),
	.Q(n271));
   NA2HDLLX0 U126 (.A(addr[1]),
	.B(addr[0]),
	.Q(n1920));
   NA2I1HDLLX0 U127 (.AN(addr[0]),
	.B(addr[1]),
	.Q(n1910));
   NA2I1HDLLX0 U128 (.AN(addr[1]),
	.B(addr[0]),
	.Q(n1900));
   NO2I1HDLLX1 U129 (.AN(clk_reg_gate_d1),
	.B(clk_reg_gate_d2),
	.Q(clk_reg));
   NA2I1HDLLX0 U130 (.AN(adc_ready_z[2]),
	.B(adc_ready_z[1]),
	.Q(n273));
   INHDLLX0 U131 (.A(n153),
	.Q(n660));
   INHDLLX0 U132 (.A(n153),
	.Q(n52));
   INHDLLX0 U133 (.A(n153),
	.Q(n50));
   INHDLLX0 U134 (.A(n381),
	.Q(n1));
   INHDLLX0 U135 (.A(n1),
	.Q(Rec_1[0]));
   INHDLLX0 U136 (.A(n374),
	.Q(n3));
   INHDLLX0 U137 (.A(n3),
	.Q(Rec_1[7]));
   INHDLLX0 U138 (.A(n373),
	.Q(n5));
   INHDLLX0 U139 (.A(n5),
	.Q(Rec_1[8]));
   INHDLLX0 U140 (.A(n372),
	.Q(n7));
   INHDLLX0 U141 (.A(n7),
	.Q(Rec_1[9]));
   INHDLLX0 U142 (.A(n371),
	.Q(n9));
   INHDLLX0 U143 (.A(n9),
	.Q(Rec_1[10]));
   INHDLLX0 U144 (.A(n369),
	.Q(n11));
   INHDLLX0 U145 (.A(n11),
	.Q(Rec_0[0]));
   INHDLLX0 U146 (.A(n362),
	.Q(n13));
   INHDLLX0 U147 (.A(n13),
	.Q(Rec_0[7]));
   INHDLLX0 U148 (.A(n361),
	.Q(n15));
   INHDLLX0 U149 (.A(n15),
	.Q(Rec_0[8]));
   INHDLLX0 U150 (.A(n360),
	.Q(n17));
   INHDLLX0 U151 (.A(n17),
	.Q(Rec_0[9]));
   INHDLLX0 U152 (.A(n359),
	.Q(n19));
   INHDLLX0 U153 (.A(n19),
	.Q(Rec_0[10]));
   INHDLLX0 U154 (.A(n380),
	.Q(n21));
   INHDLLX0 U155 (.A(n21),
	.Q(Rec_1[1]));
   INHDLLX0 U156 (.A(n379),
	.Q(n23));
   INHDLLX0 U157 (.A(n23),
	.Q(Rec_1[2]));
   INHDLLX0 U158 (.A(n378),
	.Q(n25));
   INHDLLX0 U159 (.A(n25),
	.Q(Rec_1[3]));
   INHDLLX0 U160 (.A(n377),
	.Q(n27));
   INHDLLX0 U161 (.A(n27),
	.Q(Rec_1[4]));
   INHDLLX0 U162 (.A(n376),
	.Q(n29));
   INHDLLX0 U163 (.A(n29),
	.Q(Rec_1[5]));
   INHDLLX0 U164 (.A(n375),
	.Q(n31));
   INHDLLX0 U165 (.A(n31),
	.Q(Rec_1[6]));
   INHDLLX0 U166 (.A(n368),
	.Q(n33));
   INHDLLX0 U167 (.A(n33),
	.Q(Rec_0[1]));
   INHDLLX0 U168 (.A(n367),
	.Q(n35));
   INHDLLX0 U169 (.A(n35),
	.Q(Rec_0[2]));
   INHDLLX0 U170 (.A(n366),
	.Q(n37));
   INHDLLX0 U171 (.A(n37),
	.Q(Rec_0[3]));
   INHDLLX0 U172 (.A(n365),
	.Q(n39));
   INHDLLX0 U173 (.A(n39),
	.Q(Rec_0[4]));
   INHDLLX0 U174 (.A(n364),
	.Q(n41));
   INHDLLX0 U175 (.A(n41),
	.Q(Rec_0[5]));
   INHDLLX0 U176 (.A(n363),
	.Q(n43));
   INHDLLX0 U177 (.A(n43),
	.Q(Rec_0[6]));
   INHDLLX0 U178 (.A(n370),
	.Q(n45));
   INHDLLX0 U179 (.A(n45),
	.Q(Rec_1[11]));
   INHDLLX0 U180 (.A(n358),
	.Q(n47));
   INHDLLX0 U181 (.A(n47),
	.Q(Rec_0[11]));
   ITLHDLLX12 U182 (.A(n49),
	.EN(n50),
	.Q(data_out[13]));
   ITLHDLLX12 U183 (.A(n51),
	.EN(n52),
	.Q(data_out[14]));
   ITLHDLLX12 U184 (.A(n530),
	.EN(n50),
	.Q(data_out[12]));
   ITLHDLLX12 U185 (.A(n540),
	.EN(n50),
	.Q(data_out[11]));
   ITLHDLLX12 U186 (.A(n550),
	.EN(n660),
	.Q(data_out[10]));
   ITLHDLLX12 U187 (.A(n560),
	.EN(n52),
	.Q(data_out[9]));
   ITLHDLLX12 U188 (.A(n570),
	.EN(n660),
	.Q(data_out[8]));
   ITLHDLLX12 U189 (.A(n590),
	.EN(n152),
	.Q(data_out[7]));
   ITLHDLLX12 U190 (.A(n61),
	.EN(n152),
	.Q(data_out[6]));
   ITLHDLLX12 U191 (.A(n62),
	.EN(n152),
	.Q(data_out[5]));
   ITLHDLLX12 U192 (.A(n63),
	.EN(n152),
	.Q(data_out[4]));
   ITLHDLLX12 U193 (.A(n64),
	.EN(n152),
	.Q(data_out[3]));
   ITLHDLLX12 U194 (.A(n650),
	.EN(n660),
	.Q(data_out[2]));
   ITLHDLLX12 U195 (.A(n670),
	.EN(n152),
	.Q(data_out[1]));
   ITLHDLLX12 U196 (.A(n680),
	.EN(n152),
	.Q(data_out[0]));
   INHDLLX0 U197 (.A(n387),
	.Q(n690));
   INHDLLX0 U198 (.A(n690),
	.Q(Rec_2[6]));
   INHDLLX0 U199 (.A(n388),
	.Q(n710));
   INHDLLX0 U200 (.A(n710),
	.Q(Rec_2[5]));
   INHDLLX0 U201 (.A(n389),
	.Q(n730));
   INHDLLX0 U202 (.A(n730),
	.Q(Rec_2[4]));
   INHDLLX0 U203 (.A(n390),
	.Q(n750));
   INHDLLX0 U204 (.A(n750),
	.Q(Rec_2[3]));
   INHDLLX0 U205 (.A(n391),
	.Q(n770));
   INHDLLX0 U206 (.A(n770),
	.Q(Rec_2[2]));
   INHDLLX0 U207 (.A(n392),
	.Q(n79));
   INHDLLX0 U208 (.A(n79),
	.Q(Rec_2[1]));
   INHDLLX0 U209 (.A(n399),
	.Q(n81));
   INHDLLX0 U210 (.A(n81),
	.Q(Rec_3[6]));
   INHDLLX0 U211 (.A(n400),
	.Q(n830));
   INHDLLX0 U214 (.A(n830),
	.Q(Rec_3[5]));
   INHDLLX0 U215 (.A(n401),
	.Q(n85));
   INHDLLX0 U216 (.A(n85),
	.Q(Rec_3[4]));
   INHDLLX0 U217 (.A(n402),
	.Q(n87));
   INHDLLX0 U218 (.A(n87),
	.Q(Rec_3[3]));
   INHDLLX0 U219 (.A(n403),
	.Q(n89));
   INHDLLX0 U220 (.A(n89),
	.Q(Rec_3[2]));
   INHDLLX0 U221 (.A(n404),
	.Q(n91));
   INHDLLX0 U222 (.A(n91),
	.Q(Rec_3[1]));
   INHDLLX0 U223 (.A(n406),
	.Q(n93));
   INHDLLX0 U224 (.A(n93),
	.Q(D_HP[3]));
   INHDLLX0 U225 (.A(n407),
	.Q(n95));
   INHDLLX0 U226 (.A(n95),
	.Q(D_HP[2]));
   INHDLLX0 U227 (.A(n408),
	.Q(n970));
   INHDLLX0 U228 (.A(n970),
	.Q(D_HP[1]));
   INHDLLX0 U229 (.A(n409),
	.Q(n99));
   INHDLLX0 U230 (.A(n99),
	.Q(D_HP[0]));
   INHDLLX0 U231 (.A(n383),
	.Q(n101));
   INHDLLX0 U232 (.A(n101),
	.Q(Rec_2[10]));
   INHDLLX0 U233 (.A(n384),
	.Q(n103));
   INHDLLX0 U234 (.A(n103),
	.Q(Rec_2[9]));
   INHDLLX0 U235 (.A(n385),
	.Q(n105));
   INHDLLX0 U236 (.A(n105),
	.Q(Rec_2[8]));
   INHDLLX0 U237 (.A(n386),
	.Q(n1070));
   INHDLLX0 U238 (.A(n1070),
	.Q(Rec_2[7]));
   INHDLLX0 U239 (.A(n393),
	.Q(n109));
   INHDLLX0 U240 (.A(n109),
	.Q(Rec_2[0]));
   INHDLLX0 U241 (.A(n395),
	.Q(n111));
   INHDLLX0 U242 (.A(n111),
	.Q(Rec_3[10]));
   INHDLLX0 U243 (.A(n396),
	.Q(n113));
   INHDLLX0 U244 (.A(n113),
	.Q(Rec_3[9]));
   INHDLLX0 U245 (.A(n397),
	.Q(n115));
   INHDLLX0 U246 (.A(n115),
	.Q(Rec_3[8]));
   INHDLLX0 U247 (.A(n398),
	.Q(n117));
   INHDLLX0 U248 (.A(n117),
	.Q(Rec_3[7]));
   INHDLLX0 U249 (.A(n405),
	.Q(n119));
   INHDLLX0 U250 (.A(n119),
	.Q(Rec_3[0]));
   INHDLLX0 U251 (.A(n382),
	.Q(n121));
   INHDLLX0 U252 (.A(n121),
	.Q(Rec_2[11]));
   INHDLLX0 U253 (.A(n394),
	.Q(n123));
   INHDLLX0 U254 (.A(n123),
	.Q(Rec_3[11]));
   INHDLLX12 U255 (.A(n125),
	.Q(data_to_post[12]));
   INHDLLX12 U256 (.A(n127),
	.Q(data_to_post[11]));
   INHDLLX12 U257 (.A(n129),
	.Q(data_to_post[10]));
   INHDLLX12 U258 (.A(n131),
	.Q(data_to_post[9]));
   INHDLLX12 U259 (.A(n133),
	.Q(data_to_post[8]));
   INHDLLX12 U260 (.A(n135),
	.Q(data_to_post[7]));
   INHDLLX12 U261 (.A(n137),
	.Q(data_to_post[6]));
   INHDLLX12 U262 (.A(n139),
	.Q(data_to_post[5]));
   INHDLLX12 U263 (.A(n141),
	.Q(data_to_post[4]));
   INHDLLX12 U264 (.A(n143),
	.Q(data_to_post[3]));
   INHDLLX12 U265 (.A(n145),
	.Q(data_to_post[2]));
   INHDLLX12 U266 (.A(n147),
	.Q(data_to_post[1]));
   INHDLLX12 U267 (.A(n149),
	.Q(data_to_post[0]));
   ITLHDLLX12 U268 (.A(n151),
	.EN(n152),
	.Q(data_out[15]));
   NA2HDLLX0 U269 (.A(code[2]),
	.B(code[3]),
	.Q(n218));
   AN211HDLLX0 U270 (.A(n264),
	.B(n272),
	.C(n274),
	.D(adc_ready_pos),
	.Q(N55));
   EN2HDLLX0 U271 (.A(addr[5]),
	.B(reg_map_addr[3]),
	.Q(n157));
   EN2HDLLX0 U272 (.A(addr[2]),
	.B(reg_map_addr[0]),
	.Q(n156));
   EN2HDLLX0 U273 (.A(addr[4]),
	.B(reg_map_addr[2]),
	.Q(n155));
   EN2HDLLX0 U274 (.A(addr[3]),
	.B(reg_map_addr[1]),
	.Q(n154));
   EN2HDLLX0 U275 (.A(reg_map_addr[7]),
	.B(addr[9]),
	.Q(n161));
   EN2HDLLX0 U276 (.A(reg_map_addr[6]),
	.B(addr[8]),
	.Q(n160));
   EN2HDLLX0 U277 (.A(reg_map_addr[5]),
	.B(addr[7]),
	.Q(n159));
   EN2HDLLX0 U278 (.A(reg_map_addr[4]),
	.B(addr[6]),
	.Q(n158));
   NO2I1HDLLX0 U279 (.AN(code[2]),
	.B(code[3]),
	.Q(n222));
   INHDLLX0 U280 (.A(n222),
	.Q(n164));
   NO2HDLLX0 U281 (.A(code[5]),
	.B(n164),
	.Q(n176));
   NO2HDLLX0 U282 (.A(n1920),
	.B(n210),
	.Q(N104));
   NO2HDLLX0 U283 (.A(n271),
	.B(n165),
	.Q(n2030));
   AN22HDLLX0 U284 (.A(n255),
	.B(n372),
	.C(n254),
	.D(n396),
	.Q(n168));
   AN22HDLLX0 U285 (.A(n253),
	.B(n360),
	.C(n252),
	.D(n384),
	.Q(n167));
   NA2HDLLX0 U286 (.A(n168),
	.B(n167),
	.Q(N202));
   AN22HDLLX0 U287 (.A(n255),
	.B(n373),
	.C(n254),
	.D(n397),
	.Q(n170));
   AN22HDLLX0 U288 (.A(n253),
	.B(n361),
	.C(n252),
	.D(n385),
	.Q(n169));
   NA2HDLLX0 U289 (.A(n170),
	.B(n169),
	.Q(N201));
   AN22HDLLX0 U290 (.A(n255),
	.B(n370),
	.C(n254),
	.D(n394),
	.Q(n172));
   AN22HDLLX0 U291 (.A(n253),
	.B(n358),
	.C(n252),
	.D(n382),
	.Q(n171));
   NA2HDLLX0 U292 (.A(n172),
	.B(n171),
	.Q(N204));
   AN22HDLLX0 U293 (.A(n255),
	.B(n371),
	.C(n254),
	.D(n395),
	.Q(n174));
   AN22HDLLX0 U294 (.A(n253),
	.B(n359),
	.C(n252),
	.D(n383),
	.Q(n173));
   NA2HDLLX0 U295 (.A(n174),
	.B(n173),
	.Q(N203));
   INHDLLX0 U296 (.A(n269),
	.Q(clk_data_out_buf_gate));
   BUHDLLX1 U297 (.A(rst_n),
	.Q(n330));
   BUHDLLX1 U298 (.A(rst_n),
	.Q(n333));
   BUHDLLX1 U299 (.A(rst_n),
	.Q(n332));
   BUHDLLX1 U300 (.A(rst_n),
	.Q(n331));
   BUHDLLX1 U301 (.A(rst_n),
	.Q(n334));
   BUHDLLX1 U302 (.A(rst_n),
	.Q(n329));
   BUHDLLX1 U303 (.A(rst_n),
	.Q(n328));
   BUHDLLX1 U304 (.A(rst_n),
	.Q(n335));
   NO2HDLLX0 U305 (.A(code[5]),
	.B(code[0]),
	.Q(n208));
   INHDLLX0 U306 (.A(N104),
	.Q(n177));
   AN32HDLLX0 U307 (.A(n214),
	.B(n177),
	.C(n394),
	.D(data_in[11]),
	.E(N104),
	.Q(n179));
   NA2HDLLX0 U308 (.A(n179),
	.B(n185),
	.Q(n350));
   NO2HDLLX0 U309 (.A(n1910),
	.B(n210),
	.Q(N97));
   INHDLLX0 U310 (.A(N97),
	.Q(n180));
   AN32HDLLX0 U311 (.A(n214),
	.B(n180),
	.C(n382),
	.D(data_in[11]),
	.E(N97),
	.Q(n181));
   NA2HDLLX0 U312 (.A(n181),
	.B(n185),
	.Q(n351));
   NO3HDLLX0 U313 (.A(addr[1]),
	.B(addr[0]),
	.C(n210),
	.Q(N83));
   INHDLLX0 U314 (.A(N83),
	.Q(n182));
   AN32HDLLX0 U315 (.A(n214),
	.B(n182),
	.C(n358),
	.D(data_in[11]),
	.E(N83),
	.Q(n183));
   NA2HDLLX0 U316 (.A(n183),
	.B(n185),
	.Q(n353));
   NO2HDLLX0 U317 (.A(n1900),
	.B(n210),
	.Q(N90));
   INHDLLX0 U318 (.A(N90),
	.Q(n184));
   AN32HDLLX0 U319 (.A(n214),
	.B(n184),
	.C(n370),
	.D(data_in[11]),
	.E(N90),
	.Q(n186));
   NA2HDLLX0 U320 (.A(n186),
	.B(n185),
	.Q(n352));
   NA2HDLLX0 U321 (.A(block_cnt[1]),
	.B(block_cnt[0]),
	.Q(n272));
   AND3HDLLX0 U322 (.A(block_cnt[0]),
	.B(block_cnt[1]),
	.C(block_cnt[2]),
	.Q(n274));
   INHDLLX0 U323 (.A(block_cnt[5]),
	.Q(n188));
   NA2HDLLX0 U324 (.A(block_cnt[3]),
	.B(n274),
	.Q(n321));
   NO2HDLLX0 U325 (.A(n326),
	.B(n321),
	.Q(n320));
   INHDLLX0 U326 (.A(n320),
	.Q(n187));
   AN211HDLLX0 U327 (.A(n188),
	.B(n187),
	.C(n323),
	.D(adc_ready_pos),
	.Q(N58));
   AN22HDLLX0 U328 (.A(SAMP_RATE_MUX[0]),
	.B(n1970),
	.C(n2030),
	.D(n409),
	.Q(n1960));
   NA3HDLLX0 U329 (.A(code[4]),
	.B(code[1]),
	.C(n1890),
	.Q(n1930));
   AN22HDLLX0 U330 (.A(data_adc_buffer[12]),
	.B(n258),
	.C(data_adc_buffer[0]),
	.D(FE_PDN1_n256),
	.Q(n1950));
   AN22HDLLX0 U331 (.A(data_adc_buffer[24]),
	.B(FE_PDN2_n257),
	.C(data_adc_buffer[36]),
	.D(FE_PDN3_n259),
	.Q(n1940));
   AN22HDLLX0 U332 (.A(n1970),
	.B(SAMP_RATE_MUX[1]),
	.C(n2030),
	.D(n408),
	.Q(n2000));
   AN22HDLLX0 U333 (.A(n258),
	.B(data_adc_buffer[13]),
	.C(n256),
	.D(data_adc_buffer[1]),
	.Q(n1990));
   AN22HDLLX0 U334 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[25]),
	.C(FE_PDN3_n259),
	.D(data_adc_buffer[37]),
	.Q(n1980));
   AN22HDLLX0 U335 (.A(n2030),
	.B(n407),
	.C(n258),
	.D(data_adc_buffer[14]),
	.Q(n2020));
   AN22HDLLX0 U336 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[26]),
	.C(FE_PDN3_n259),
	.D(data_adc_buffer[38]),
	.Q(n2010));
   AN22HDLLX0 U337 (.A(n2030),
	.B(n406),
	.C(n258),
	.D(data_adc_buffer[15]),
	.Q(n2050));
   AN22HDLLX0 U338 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[27]),
	.C(FE_PDN3_n259),
	.D(data_adc_buffer[39]),
	.Q(n2040));
   NO3I1HDLLX0 U339 (.AN(code[4]),
	.B(code[1]),
	.C(n271),
	.Q(n207));
   AN31HDLLX0 U340 (.A(code[2]),
	.B(n268),
	.C(n267),
	.D(n207),
	.Q(n216));
   INHDLLX0 U341 (.A(n208),
	.Q(n215));
   NO2HDLLX0 U342 (.A(code[5]),
	.B(n221),
	.Q(n212));
   NO3HDLLX0 U343 (.A(code[5]),
	.B(code[0]),
	.C(n217),
	.Q(n324));
   AN211HDLLX0 U344 (.A(n212),
	.B(n219),
	.C(n324),
	.D(n211),
	.Q(n213));
   NA22HDLLX0 U345 (.A(n219),
	.B(n218),
	.C(n217),
	.Q(n220));
   AN32HDLLX0 U346 (.A(n222),
	.B(code[0]),
	.C(n267),
	.D(n221),
	.E(n220),
	.Q(n223));
   NO2HDLLX0 U347 (.A(code[5]),
	.B(n223),
	.Q(n338));
   AN22HDLLX0 U348 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[32]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[8]),
	.Q(n225));
   AN22HDLLX0 U349 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[44]),
	.C(n258),
	.D(data_adc_buffer[20]),
	.Q(n224));
   AN22HDLLX0 U350 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[33]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[9]),
	.Q(n229));
   AN22HDLLX0 U351 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[45]),
	.C(n258),
	.D(data_adc_buffer[21]),
	.Q(n228));
   AN22HDLLX0 U352 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[30]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[6]),
	.Q(n233));
   AN22HDLLX0 U353 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[42]),
	.C(n258),
	.D(data_adc_buffer[18]),
	.Q(n232));
   AN22HDLLX0 U355 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[28]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[4]),
	.Q(n237));
   AN22HDLLX0 U356 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[40]),
	.C(n258),
	.D(data_adc_buffer[16]),
	.Q(n236));
   AN22HDLLX0 U357 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[29]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[5]),
	.Q(n241));
   AN22HDLLX0 U358 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[41]),
	.C(n258),
	.D(data_adc_buffer[17]),
	.Q(n240));
   AN22HDLLX0 U359 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[35]),
	.C(n256),
	.D(data_adc_buffer[11]),
	.Q(n245));
   AN22HDLLX0 U360 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[47]),
	.C(n258),
	.D(data_adc_buffer[23]),
	.Q(n244));
   AN22HDLLX0 U361 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[34]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[10]),
	.Q(n249));
   AN22HDLLX0 U362 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[46]),
	.C(n258),
	.D(data_adc_buffer[22]),
	.Q(n248));
   AN22HDLLX0 U363 (.A(FE_PDN2_n257),
	.B(data_adc_buffer[31]),
	.C(FE_PDN1_n256),
	.D(data_adc_buffer[7]),
	.Q(n261));
   AN22HDLLX0 U364 (.A(FE_PDN3_n259),
	.B(data_adc_buffer[43]),
	.C(n258),
	.D(data_adc_buffer[19]),
	.Q(n260));
   ON31HDLLX0 U365 (.A(code[5]),
	.B(n271),
	.C(n270),
	.D(n269),
	.Q(N205));
   OA211HDLLX0 U366 (.A(block_cnt[3]),
	.B(n274),
	.C(n321),
	.D(n273),
	.Q(N56));
   NO3HDLLX0 U367 (.A(block_cnt[5]),
	.B(block_cnt[0]),
	.C(n275),
	.Q(n276));
   INHDLLX0 U368 (.A(data_adc_buffer[36]),
	.Q(n279));
   NO3HDLLX0 U369 (.A(n327),
	.B(n326),
	.C(n312),
	.Q(n286));
   AN22HDLLX0 U370 (.A(data_adc_buffer[24]),
	.B(n314),
	.C(data_adc_buffer[0]),
	.D(n315),
	.Q(n277));
   INHDLLX0 U371 (.A(data_adc_buffer[37]),
	.Q(n282));
   AN22HDLLX0 U372 (.A(data_adc_buffer[25]),
	.B(n314),
	.C(data_adc_buffer[1]),
	.D(n315),
	.Q(n280));
   AN22HDLLX0 U373 (.A(data_adc_buffer[14]),
	.B(n313),
	.C(data_from_pre_buf[2]),
	.D(n312),
	.Q(n284));
   AN22HDLLX0 U374 (.A(data_adc_buffer[26]),
	.B(n314),
	.C(data_adc_buffer[38]),
	.D(n286),
	.Q(n283));
   AN22HDLLX0 U375 (.A(data_adc_buffer[15]),
	.B(n313),
	.C(data_from_pre_buf[3]),
	.D(n312),
	.Q(n288));
   AN22HDLLX0 U376 (.A(data_adc_buffer[27]),
	.B(n314),
	.C(data_adc_buffer[39]),
	.D(n286),
	.Q(n287));
   INHDLLX0 U377 (.A(data_adc_buffer[40]),
	.Q(n293));
   AN22HDLLX0 U378 (.A(data_adc_buffer[16]),
	.B(n313),
	.C(data_from_pre_buf[4]),
	.D(n312),
	.Q(n292));
   AN22HDLLX0 U379 (.A(data_adc_buffer[4]),
	.B(n315),
	.C(data_adc_buffer[28]),
	.D(n314),
	.Q(n291));
   INHDLLX0 U380 (.A(data_adc_buffer[41]),
	.Q(n296));
   AN22HDLLX0 U381 (.A(data_adc_buffer[17]),
	.B(n313),
	.C(data_from_pre_buf[5]),
	.D(n312),
	.Q(n295));
   AN22HDLLX0 U382 (.A(data_adc_buffer[5]),
	.B(n315),
	.C(data_adc_buffer[29]),
	.D(n314),
	.Q(n294));
   INHDLLX0 U383 (.A(data_adc_buffer[42]),
	.Q(n299));
   AN22HDLLX0 U384 (.A(data_adc_buffer[18]),
	.B(n313),
	.C(data_from_pre_buf[6]),
	.D(n312),
	.Q(n298));
   AN22HDLLX0 U385 (.A(data_adc_buffer[6]),
	.B(n315),
	.C(data_adc_buffer[30]),
	.D(n314),
	.Q(n297));
   INHDLLX0 U386 (.A(data_adc_buffer[43]),
	.Q(n302));
   AN22HDLLX0 U387 (.A(data_adc_buffer[19]),
	.B(n313),
	.C(data_from_pre_buf[7]),
	.D(n312),
	.Q(n301));
   AN22HDLLX0 U388 (.A(data_adc_buffer[7]),
	.B(n315),
	.C(data_adc_buffer[31]),
	.D(n314),
	.Q(n300));
   INHDLLX0 U389 (.A(data_adc_buffer[44]),
	.Q(n305));
   AN22HDLLX0 U390 (.A(data_adc_buffer[20]),
	.B(n313),
	.C(data_from_pre_buf[8]),
	.D(n312),
	.Q(n304));
   AN22HDLLX0 U391 (.A(data_adc_buffer[8]),
	.B(n315),
	.C(data_adc_buffer[32]),
	.D(n314),
	.Q(n303));
   INHDLLX0 U392 (.A(data_adc_buffer[45]),
	.Q(n308));
   AN22HDLLX0 U393 (.A(data_adc_buffer[21]),
	.B(n313),
	.C(data_from_pre_buf[9]),
	.D(n312),
	.Q(n307));
   AN22HDLLX0 U394 (.A(data_adc_buffer[9]),
	.B(n315),
	.C(data_adc_buffer[33]),
	.D(n314),
	.Q(n306));
   INHDLLX0 U395 (.A(data_adc_buffer[46]),
	.Q(n311));
   AN22HDLLX0 U396 (.A(data_adc_buffer[22]),
	.B(n313),
	.C(data_from_pre_buf[10]),
	.D(n312),
	.Q(n310));
   AN22HDLLX0 U397 (.A(data_adc_buffer[10]),
	.B(n315),
	.C(data_adc_buffer[34]),
	.D(n314),
	.Q(n309));
   INHDLLX0 U398 (.A(data_adc_buffer[47]),
	.Q(n319));
   AN22HDLLX0 U399 (.A(data_adc_buffer[23]),
	.B(n313),
	.C(data_from_pre_buf[11]),
	.D(n312),
	.Q(n317));
   AN22HDLLX0 U400 (.A(data_adc_buffer[11]),
	.B(n315),
	.C(data_adc_buffer[35]),
	.D(n314),
	.Q(n316));
   AN211HDLLX0 U401 (.A(n326),
	.B(n321),
	.C(n320),
	.D(adc_ready_pos),
	.Q(N57));
   NO2HDLLX0 U402 (.A(block_cnt[6]),
	.B(n323),
	.Q(n322));
   AN211HDLLX0 U403 (.A(block_cnt[6]),
	.B(n323),
	.C(adc_ready_pos),
	.D(n322),
	.Q(N59));
   OA22HDLLX0 U404 (.A(n325),
	.B(data_in[0]),
	.C(SAMP_RATE_MUX[0]),
	.D(n324),
	.Q(n580));
   OA22HDLLX0 U405 (.A(n325),
	.B(data_in[1]),
	.C(SAMP_RATE_MUX[1]),
	.D(n324),
	.Q(n60));
endmodule

module BLOCK_DIGITAL (
	clk_3p2M, 
	rst_n, 
	data_in, 
	addr, 
	code, 
	reg_map_addr, 
	data_out, 
	Rec_0, 
	Rec_1, 
	Rec_2, 
	Rec_3, 
	D_HP, 
	data_from_pre, 
	data_to_post, 
	COMP, 
	SAMP, 
	SAMP_analog, 
	WP0, 
	WP1, 
	WP2, 
	WP3);
   input clk_3p2M;
   input rst_n;
   input [15:0] data_in;
   input [9:0] addr;
   input [5:0] code;
   input [7:0] reg_map_addr;
   inout [15:0] data_out;
   output [11:0] Rec_0;
   output [11:0] Rec_1;
   output [11:0] Rec_2;
   output [11:0] Rec_3;
   output [3:0] D_HP;
   input [12:0] data_from_pre;
   output [12:0] data_to_post;
   input [3:0] COMP;
   output SAMP;
   output SAMP_analog;
   output [11:0] WP0;
   output [11:0] WP1;
   output [11:0] WP2;
   output [11:0] WP3;

   // Internal wires
   wire FE_PDN4_COMP_3;
   wire CTS_2;
   wire CTS_1;
   wire n59;
   wire rst_syn_n;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire [11:0] data_from_adc0;
   wire [11:0] data_from_adc1;
   wire [11:0] data_from_adc2;
   wire [11:0] data_from_adc3;
   wire [1:0] SAMP_RATE_MUX;

   BUHDLLX1 FE_PDC4_COMP_3 (.A(COMP[3]),
	.Q(FE_PDN4_COMP_3));
   BUHDLLX3 CTS_ccl_a_buf_00006 (.A(CTS_2),
	.Q(CTS_1));
   BUHDLLX2 CTS_ccl_a_buf_00009 (.A(clk_3p2M),
	.Q(CTS_2));
   RST_N_SYN rst_n_syn (.rst_n(rst_n),
	.rst_syn_n(rst_syn_n),
	.clk_sys(CTS_1));
   FSM_BLOCK fsm_block (.clk(clk_3p2M),
	.rst_n(n58),
	.data_in({ data_in[15],
		data_in[14],
		data_in[13],
		data_in[12],
		n31,
		n25,
		n23,
		n21,
		n19,
		n37,
		n35,
		n33,
		n45,
		n43,
		n51,
		n47 }),
	.addr({ n17,
		n15,
		n13,
		n11,
		n9,
		n7,
		n5,
		n3,
		n55,
		n53 }),
	.code({ n57,
		n29,
		n41,
		n49,
		n27,
		n39 }),
	.data_out(data_out),
	.reg_map_addr(reg_map_addr),
	.SAMP_RATE_MUX(SAMP_RATE_MUX),
	.adc_ready(n59),
	.data_from_adc0(data_from_adc0),
	.data_from_adc1(data_from_adc1),
	.data_from_adc2(data_from_adc2),
	.data_from_adc3(data_from_adc3),
	.data_from_pre(data_from_pre),
	.data_to_post(data_to_post),
	.Rec_0(Rec_0),
	.Rec_1(Rec_1),
	.Rec_2(Rec_2),
	.Rec_3(Rec_3),
	.D_HP(D_HP),
	.clk_clone1(CTS_1),
	.clk_clone2(CTS_2));
   sar_adc_logic_12bit_v4_single_input_v2_x4 sar_adc_logic (.D0(data_from_adc0),
	.D1(data_from_adc1),
	.D2(data_from_adc2),
	.D3(data_from_adc3),
	.DR(n59),
	.SAMP_analog(SAMP_analog),
	.WP0(WP0),
	.WP1(WP1),
	.WP2(WP2),
	.WP3(WP3),
	.COMP({ FE_PDN4_COMP_3,
		COMP[2],
		COMP[1],
		COMP[0] }),
	.RSTN(n58),
	.SAMP_RATE_MUX(SAMP_RATE_MUX),
	.CLK(CTS_1),
	.CLK_clone1(clk_3p2M));
   BUHDLLX0 U1 (.A(n59),
	.Q(SAMP));
   INHDLLX0 U2 (.A(n26),
	.Q(n27));
   INHDLLX0 U3 (.A(n28),
	.Q(n29));
   INHDLLX0 U4 (.A(n48),
	.Q(n49));
   INHDLLX0 U5 (.A(n52),
	.Q(n53));
   INHDLLX0 U6 (.A(n54),
	.Q(n55));
   INHDLLX0 U7 (.A(n56),
	.Q(n57));
   INHDLLX0 U8 (.A(n40),
	.Q(n41));
   INHDLLX0 U9 (.A(n38),
	.Q(n39));
   INHDLLX0 U10 (.A(addr[2]),
	.Q(n2));
   INHDLLX0 U11 (.A(n2),
	.Q(n3));
   INHDLLX0 U12 (.A(addr[3]),
	.Q(n4));
   INHDLLX0 U13 (.A(n4),
	.Q(n5));
   INHDLLX0 U14 (.A(addr[4]),
	.Q(n6));
   INHDLLX0 U15 (.A(n6),
	.Q(n7));
   INHDLLX0 U16 (.A(addr[5]),
	.Q(n8));
   INHDLLX0 U17 (.A(n8),
	.Q(n9));
   INHDLLX0 U18 (.A(addr[6]),
	.Q(n10));
   INHDLLX0 U19 (.A(n10),
	.Q(n11));
   INHDLLX0 U20 (.A(addr[7]),
	.Q(n12));
   INHDLLX0 U21 (.A(n12),
	.Q(n13));
   INHDLLX0 U22 (.A(addr[8]),
	.Q(n14));
   INHDLLX0 U23 (.A(n14),
	.Q(n15));
   INHDLLX0 U24 (.A(addr[9]),
	.Q(n16));
   INHDLLX0 U25 (.A(n16),
	.Q(n17));
   INHDLLX0 U26 (.A(data_in[7]),
	.Q(n18));
   INHDLLX0 U27 (.A(n18),
	.Q(n19));
   INHDLLX0 U28 (.A(data_in[8]),
	.Q(n20));
   INHDLLX0 U29 (.A(n20),
	.Q(n21));
   INHDLLX0 U30 (.A(data_in[9]),
	.Q(n22));
   INHDLLX0 U31 (.A(n22),
	.Q(n23));
   INHDLLX0 U32 (.A(data_in[10]),
	.Q(n24));
   INHDLLX0 U33 (.A(n24),
	.Q(n25));
   INHDLLX0 U34 (.A(code[1]),
	.Q(n26));
   INHDLLX0 U35 (.A(code[4]),
	.Q(n28));
   INHDLLX0 U36 (.A(data_in[11]),
	.Q(n30));
   INHDLLX0 U37 (.A(n30),
	.Q(n31));
   INHDLLX0 U38 (.A(data_in[4]),
	.Q(n32));
   INHDLLX0 U39 (.A(n32),
	.Q(n33));
   INHDLLX0 U40 (.A(data_in[5]),
	.Q(n34));
   INHDLLX0 U41 (.A(n34),
	.Q(n35));
   INHDLLX0 U42 (.A(data_in[6]),
	.Q(n36));
   INHDLLX0 U43 (.A(n36),
	.Q(n37));
   INHDLLX0 U44 (.A(code[0]),
	.Q(n38));
   INHDLLX0 U45 (.A(code[3]),
	.Q(n40));
   INHDLLX0 U46 (.A(data_in[2]),
	.Q(n42));
   INHDLLX0 U47 (.A(n42),
	.Q(n43));
   INHDLLX0 U48 (.A(data_in[3]),
	.Q(n44));
   INHDLLX0 U49 (.A(n44),
	.Q(n45));
   INHDLLX0 U50 (.A(data_in[0]),
	.Q(n46));
   INHDLLX0 U51 (.A(n46),
	.Q(n47));
   INHDLLX0 U52 (.A(code[2]),
	.Q(n48));
   INHDLLX0 U53 (.A(data_in[1]),
	.Q(n50));
   INHDLLX0 U54 (.A(n50),
	.Q(n51));
   INHDLLX0 U55 (.A(addr[0]),
	.Q(n52));
   INHDLLX0 U56 (.A(addr[1]),
	.Q(n54));
   INHDLLX0 U57 (.A(code[5]),
	.Q(n56));
   BUHDLLX1 U58 (.A(rst_syn_n),
	.Q(n58));
endmodule

